# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C++ backend entry points
#'
#' Low-level C++ entry points exposed to R via Rcpp.
#' These create and operate on an opaque backend handle (external pointer)
#' used to evaluate objective, gradient, and Hessian values.
#'
#' @param data An R list containing model data objects required by the backend
#'   (used by \code{getAdFun()}).
#' @param config An R list of configuration options required by the backend
#'   (used by \code{getAdFun()}).
#' @param x Numeric parameter vector of length \code{Nparams}.
#' @param backendContext External pointer returned by \code{getAdFun()}.
#' @param inner Logical scalar. If \code{TRUE}, evaluate inner-\eqn{\gamma}
#'   derivatives; otherwise evaluate outer/full derivatives.
#' @param Sgroups Optional integer vector of 0-based group indices to evaluate.
#'   If omitted, uses all groups \code{0:(Ngroups-1)}.
#' @param LinvPt Sparse \code{dgCMatrix} for columns of
#'   \eqn{P^\top L^{-1} D^{-1/2}} (or equivalent) used in trace contractions.
#' @param LinvPtColumns Sparse \code{ngCMatrix}/\code{dgCMatrix} mapping
#'   selected columns of \code{LinvPt} to each group.
#'
#' @return
#' \itemize{
#'   \item \code{getAdFun}: external pointer handle with backend state.
#'   \item \code{jointLogDens}: scalar objective value summed over groups.
#'   \item \code{grad}: numeric gradient vector.
#'   \item \code{hess}: sparse symmetric Hessian as a Matrix
#'     \code{dsCMatrix} object.
#'   \item \code{traceHinvT}: numeric vector of third-derivative contractions.
#' }
#'
#' @details
#' The external pointer returned by \code{getAdFun()} is opaque and not
#' user-modifiable. It may hold substantial memory (AD tapes, sparsity maps,
#' work caches). Do not save it across R sessions.
#'
#' @name adlaplace_cpp
NULL

#' @rdname adlaplace_cpp
#' @export
getAdFun <- function(data, config) {
    .Call(`_adlaplace_getAdFun`, data, config)
}

#' @rdname adlaplace_cpp
#' @export
jointLogDens <- function(x, backendContext, Sgroups = NULL) {
    .Call(`_adlaplace_jointLogDens`, x, backendContext, Sgroups)
}

#' @rdname adlaplace_cpp
#' @export
grad <- function(x, backendContext, inner = FALSE, Sgroups = NULL) {
    .Call(`_adlaplace_grad`, x, backendContext, inner, Sgroups)
}

#' @rdname adlaplace_cpp
#' @export
hess <- function(x, backendContext, inner = FALSE, Sgroups = NULL) {
    .Call(`_adlaplace_hess`, x, backendContext, inner, Sgroups)
}

#' @rdname adlaplace_cpp
#' @export
traceHinvT <- function(x, LinvPt, LinvPtColumns, backendContext, Sgroups = NULL) {
    .Call(`_adlaplace_traceHinvT`, x, LinvPt, LinvPtColumns, backendContext, Sgroups)
}

#' Register C-callable entry points
register_callables <- function() {
    .Call(`_adlaplace_register_callables`)
}

#' Inner optimization over gamma using trust-region CG (sparse)
#'
#' Runs the inner optimization problem (typically over \eqn{\gamma}) using the
#' trustOptim sparse trust-region Conjugate Gradient solver. This function
#' evaluates the objective, gradient, and Hessian through the pre-built AD pack
#' (external pointer) and returns the solution along with curvature information.
#'
#' @param x Numeric full parameter vector of length \code{Nparams}, used by
#'   \code{all_derivs()} for outer/full derivatives.
#' @param parameters Numeric vector of fixed outer parameters
#'   (\code{beta}, \code{theta}; length \code{Nbeta+Ntheta}) used by
#'   \code{inner_opt()}.
#' @param gamma Numeric vector of starting values for inner parameters
#'   (\code{gamma}; length \code{Ngamma}) used by \code{inner_opt()}.
#' @param data Data list used to construct the AD backend when \code{adFun}
#'   is not supplied.
#' @param adFun External pointer created by \code{getAdFun()} (class
#'   \code{"adlaplace_handle_ptr"}), or a list containing element \code{adFun}.
#' @param config Configuration list. Must include \code{gamma}, fixed
#'   \code{beta}/\code{theta}, and group/sparsity settings.
#' @param control List of trust-region control parameters (see
#'   \code{trustOptim}).
#' @param adFun Optional backend handle/list from \code{getAdFun()}.
#'   If provided, it is reused.
#'
#' @return A list with components:
#' \itemize{
#'   \item \code{all_derivs}: list with \code{fval}, \code{gradient}, and
#'         \code{hessian} for the outer/full derivatives (\code{inner=FALSE}).
#'   \item \code{minusLogLik}: scalar \eqn{-\ell(\hat\gamma)} plus the Laplace
#'         correction \eqn{\tfrac{1}{2}\log|H| + \tfrac{n}{2}\log(2\pi)}.
#'   \item \code{fval}: scalar objective at the solution (typically \eqn{-\ell}).
#'   \item \code{halfLogDet}: \eqn{\tfrac{1}{2}\log|H|} from sparse LDLT.
#'   \item \code{solution}: optimized parameter vector (length \code{Ngamma}).
#'   \item \code{gradient}: gradient at solution (length \code{Ngamma}).
#'   \item \code{hessian}: Hessian as a dgCMatrix-like list with slots
#'         \code{i,p,x,Dim} (0-based indices).
#'   \item \code{cholHessian}: sparse LDLT factors as a list with
#'         \code{P} (permutation indices), \code{D} (diagonal), and
#'         \code{L} (lower-triangular factor in dgCMatrix-like form).
#'   \item \code{iterations}: number of trust-region iterations.
#'   \item \code{status}: solver status string.
#'   \item \code{trust.radius}: final trust-region radius.
#'   \item \code{method}: character, here \code{"Sparse"}.
#' }
#'
#' @details
#' This calls the sparse method from the \code{TrustOptim} package via the Cpp interface.  
#'
#' @name innerOpt
NULL

#' @rdname innerOpt
#' @export
all_derivs <- function(x, adFun, config) {
    .Call(`_adlaplace_all_derivs`, x, adFun, config)
}

#' @rdname innerOpt
#' @export
inner_opt <- function(parameters, gamma, config, control, adFun = NULL) {
    .Call(`_adlaplace_inner_opt`, parameters, gamma, config, control, adFun)
}

