# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Build raw AD handle for observation shards only
#'
#' @param model An \code{ad_data} S4 object.
#' @param config Model configuration list.
#' @param name Registered observation density name (e.g. \code{"nbinom_obs"}).
#' @return External pointer of class \code{ad_fun_ptr}.
#' @keywords internal
get_ad_fun_raw_obs <- function(model, config, name) {
    .Call(`_adlaplace_get_ad_fun_raw_obs`, model, config, name)
}

#' Build raw AD handle for a random-effect shard
#'
#' @param model An \code{ad_data} S4 object (maps for the term).
#' @param precision Numeric vector of diagonal precision weights (required).
#' @param config Model configuration list.
#' @param name Registered random density name (e.g. \code{"random_diagonal"}).
#' @return External pointer of class \code{ad_fun_ptr}.
#' @keywords internal
get_ad_fun_raw_random <- function(model, precision, config, name) {
    .Call(`_adlaplace_get_ad_fun_raw_random`, model, precision, config, name)
}

#' Build raw AD handle for a parameters shard
#'
#' @param model An \code{ad_data} S4 object.
#' @param config Model configuration list.
#' @param name Registered parameters density name (e.g. \code{"nbinom_extra"}).
#' @return External pointer of class \code{ad_fun_ptr}.
#' @keywords internal
get_ad_fun_raw_parameters <- function(model, config, name) {
    .Call(`_adlaplace_get_ad_fun_raw_parameters`, model, config, name)
}

#' Merge partial AD handles into one raw handle
#'
#' Concatenates shards from \code{\link{ad_fun_ptr}} (or other partial
#' builders) in list order. Does not attach \code{hessian_map}; use
#' \code{\link{ad_fun}} when templates are needed.
#'
#' @param handles List of external pointers (\code{ad_fun_ptr}).
#' @return Combined external pointer of class \code{ad_fun_ptr}.
#' @seealso \code{\link{ad_fun_ptr}}, \code{\link{ad_fun}}
#' @keywords internal
c_ad_fun_ptr <- function(handles) {
    .Call(`_adlaplace_c_ad_fun_ptr`, handles)
}

#' Attach hessian_map() result to an ad_fun handle
#'
#' Copies outer/inner templates and maps into the C++ \code{ad_fun} handle.
#'
#' @param handle External pointer of class \code{ad_fun_ptr}.
#' @param hessian_pack List returned by \code{hessian_map()}.
#' @keywords internal
adlaplace_attach_hessian <- function(handle, hessian_pack) {
    invisible(.Call(`_adlaplace_adlaplace_attach_hessian`, handle, hessian_pack))
}

#' Number of AD shards in an \code{ad_fun_ptr} handle
#'
#' @param handle External pointer of class \code{ad_fun_ptr}.
#' @return Integer count of groups (shards).
#' @export
n_groups <- function(handle) {
    .Call(`_adlaplace_n_groups`, handle)
}

#' Sparse structure sizes for one AD shard
#'
#' Layout and sparsity sizes for one AD shard
#'
#' @param handle External pointer of class \code{ad_fun_ptr}.
#' @param group 0-based group index.
#' @return List with \code{n_inner}, \code{n_outer}, \code{n_beta}, \code{n_theta},
#'   and \code{nnz_grad_*}, \code{nnz_hes_*}.
#' @keywords internal
get_sizes <- function(handle, group) {
    .Call(`_adlaplace_get_sizes`, handle, group)
}

#' Sparse index patterns for one AD shard
#'
#' @param handle External pointer of class \code{ad_fun_ptr}.
#' @param group 0-based group index.
#' @return List with \code{grad}, \code{grad_inner}, \code{row_hess}, \code{col_hess}, etc.
#' @keywords internal
get_sparse_pattern <- function(handle, group) {
    .Call(`_adlaplace_get_sparse_pattern`, handle, group)
}

#' Deep copy of an \code{ad_fun_ptr} handle
#'
#' Clones CppAD tapes and sparsity patterns into a new external pointer.
#' The source handle is unchanged (unlike \code{c()} on \code{ad_fun_ptr}, which moves
#' shards and clears sources).
#'
#' @param handle External pointer of class \code{ad_fun_ptr}.
#' @return New \code{ad_fun_ptr} with independent C++ state.
#' @keywords internal
clone_ad_fun_ptr_ <- function(handle) {
    .Call(`_adlaplace_clone_ad_fun_ptr_impl`, handle)
}

#' @title C++ backend entry points
#' @name adlaplace_cpp
#' @description Low-level C++ entry points exposed to R via Rcpp.
#'
#' @param negative Logical (default \code{TRUE}). If \code{TRUE}, return the
#'   **negative** log density \eqn{-\ell(x)} and its derivatives (minimization /
#'   \pkg{trustOptim} sign, consistent with \code{inner_opt()}). If \code{FALSE}, return \eqn{\ell(x)}, \eqn{\nabla\ell},
#'   and \eqn{\nabla^2\ell}.
#' @param ad_fun_ptr External pointer of class \code{ad_fun_ptr}.
#' @param x Numeric parameter vector of length \code{Nparams}.
#' @param shards Optional integer vector of 0-based shard indices; \code{NULL} or
#'   \code{integer(0)} evaluates all shards.
#' @param inner Logical scalar for inner-\eqn{\gamma} vs outer derivatives.
#' @param verbose Logical passed to \code{hessian()}.
#' @param LinvPt,LinvPtColumns,num_threads See \code{traceHinvT()}.
#'
#' @section Sign convention:
#' With default \code{negative = TRUE}, \code{joint_log_dens()}, \code{grad()},
#' and \code{hessian()} match \code{inner_opt()} (negative
#' log-density). Set \code{negative = FALSE} for the joint log density and its
#' derivatives at the same \code{x}.
#'
#' @rdname adlaplace_cpp
#' @return Scalar log-density value (sign per \code{negative}).
joint_log_dens <- function(ad_fun_ptr, x, shards = NULL, negative = TRUE) {
    .Call(`_adlaplace_joint_log_dens`, ad_fun_ptr, x, shards, negative)
}

#' @rdname adlaplace_cpp
#' @return Gradient of log density (sign per \code{negative}).
grad <- function(ad_fun_ptr, x, shards = NULL, inner = FALSE, negative = TRUE) {
    .Call(`_adlaplace_grad`, ad_fun_ptr, x, shards, inner, negative)
}

#' @rdname adlaplace_cpp
#' @return Sparse Hessian of log density (sign per \code{negative}).
hessian <- function(ad_fun_ptr, x, shards = NULL, inner = FALSE, verbose = FALSE, negative = TRUE) {
    .Call(`_adlaplace_hessian`, ad_fun_ptr, x, shards, inner, verbose, negative)
}

#' Inner optimization over gamma using trust-region CG (sparse)
#'
#' Runs the inner optimization problem (typically over \eqn{\gamma}) using the
#' trustOptim sparse trust-region Conjugate Gradient solver. This function
#' evaluates the objective, gradient, and Hessian through the pre-built AD pack
#' (external pointer) and returns the solution along with curvature information.
#'
#' @param x Numeric full parameter vector of length \code{Nparams}.
#' @param parameters Numeric vector of fixed outer parameters
#'   (\code{beta}, \code{theta}; length \code{Nbeta+Ntheta}) used by
#'   \code{inner_opt()}.
#' @param gamma Numeric vector of starting values for inner parameters
#'   (\code{gamma}; length \code{Ngamma}) used by \code{inner_opt()}.
#' @param ad_fun \code{ad_fun} S4 object from \code{ad_fun(ad_fun_ptr)}.
#' @param config Configuration list with model dimensions, groups, and
#'   sparsity information.
#' @param control List of trust-region control parameters for
#'   \code{inner_opt()} (see \pkg{trustOptim}).
#' @param deriv Logical: if \code{TRUE}, return full outer gradient and Hessian at the
#'   inner solution; if \code{FALSE}, return inner quantities only (default).
#'
#' @return
#'   \item{\code{inner_opt()}}{Returns \code{log_lik}, \code{neg_log_lik}
#'   (Laplace profile likelihood and its negation), \code{fval} (inner objective:
#'   negative log joint density at \eqn{\hat\gamma}), \code{solution},
#'   \code{gradient} (list \code{inner}, \code{outer}; \code{outer} empty when
#'   \code{deriv=FALSE}), \code{hessian} (list \code{inner}, \code{outer},
#'   \code{chol_inner}, \code{half_log_det}),
#'   \code{iterations}, \code{status}, \code{trust.radius}, \code{method}.
#'   Objective and derivatives use the **negative log-density** convention.}
#'
#' @details
#' This calls the sparse method from the \code{TrustOptim} package via the Cpp interface.
#' \code{inner_opt()} negates tape log-density values in C++ for minimization.
#'
#' @name innerOpt
NULL

#' @rdname innerOpt
#' @keywords internal
inner_opt <- function(parameters, gamma, config, ad_fun, control, deriv = FALSE) {
    .Call(`_adlaplace_inner_opt`, parameters, gamma, config, ad_fun, control, deriv)
}

#' @rdname adlaplace_cpp
traceHinvT <- function(ad_fun_ptr, x, LinvPt, LinvPtColumns, num_threads, shards = NULL) {
    .Call(`_adlaplace_traceHinvT`, ad_fun_ptr, x, LinvPt, LinvPtColumns, num_threads, shards)
}

