# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
getAdFun <- function(data, config) {
    .Call(`_adlaplace_getAdFun`, data, config)
}

#' @export
jointLogDens <- function(parameters, adPack, config) {
    .Call(`_adlaplace_jointLogDens`, parameters, adPack, config)
}

#' @export
grad <- function(parameters, adPack, config) {
    .Call(`_adlaplace_grad`, parameters, adPack, config)
}

#' @export
hessian <- function(parameters, adPack, config) {
    .Call(`_adlaplace_hessian`, parameters, adPack, config)
}

#' @export
inner_opt <- function(parameters, data, control, config) {
    .Call(`_adlaplace_inner_opt`, parameters, data, control, config)
}

#' @export
inner_opt_adpack <- function(parameters, adPack, control, config) {
    .Call(`_adlaplace_inner_opt_adpack`, parameters, adPack, control, config)
}

#' @export
sparsity <- function(adPack, parameters) {
    .Call(`_adlaplace_sparsity`, adPack, parameters)
}

