// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fem_logdet_debug
Rcpp::List fem_logdet_debug(Rcpp::List precision, double range, double sd, Rcpp::Nullable<Rcpp::LogicalVector> log_scale);
RcppExport SEXP _adlaplaceFem_fem_logdet_debug(SEXP precisionSEXP, SEXP rangeSEXP, SEXP sdSEXP, SEXP log_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type precision(precisionSEXP);
    Rcpp::traits::input_parameter< double >::type range(rangeSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::LogicalVector> >::type log_scale(log_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(fem_logdet_debug(precision, range, sd, log_scale));
    return rcpp_result_gen;
END_RCPP
}
// create_ad_shard_random_fem_ssq_2
SEXP create_ad_shard_random_fem_ssq_2(SEXP model, Rcpp::List config);
RcppExport SEXP _adlaplaceFem_create_ad_shard_random_fem_ssq_2(SEXP modelSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(create_ad_shard_random_fem_ssq_2(model, config));
    return rcpp_result_gen;
END_RCPP
}
// create_ad_shard_random_fem_ssq_3
SEXP create_ad_shard_random_fem_ssq_3(SEXP model, Rcpp::List config);
RcppExport SEXP _adlaplaceFem_create_ad_shard_random_fem_ssq_3(SEXP modelSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(create_ad_shard_random_fem_ssq_3(model, config));
    return rcpp_result_gen;
END_RCPP
}
// get_ad_pack_raw_parameters
SEXP get_ad_pack_raw_parameters(SEXP model, Rcpp::List config, std::string name);
RcppExport SEXP _adlaplaceFem_get_ad_pack_raw_parameters(SEXP modelSEXP, SEXP configSEXP, SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type config(configSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    rcpp_result_gen = Rcpp::wrap(get_ad_pack_raw_parameters(model, config, name));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_adlaplaceFem_fem_logdet_debug", (DL_FUNC) &_adlaplaceFem_fem_logdet_debug, 4},
    {"_adlaplaceFem_create_ad_shard_random_fem_ssq_2", (DL_FUNC) &_adlaplaceFem_create_ad_shard_random_fem_ssq_2, 2},
    {"_adlaplaceFem_create_ad_shard_random_fem_ssq_3", (DL_FUNC) &_adlaplaceFem_create_ad_shard_random_fem_ssq_3, 2},
    {"_adlaplaceFem_get_ad_pack_raw_parameters", (DL_FUNC) &_adlaplaceFem_get_ad_pack_raw_parameters, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_adlaplaceFem(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
