# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pmvn_cpp <- function(upper, lower, mean, sigma, n_points = 1021L, n_shifts = 8L, seed = 1L) {
    .Call(`_admvn_pmvn_cpp`, upper, lower, mean, sigma, n_points, n_shifts, seed)
}

pack_genz_ch_cpp <- function(sigma, perm) {
    .Call(`_admvn_pack_genz_ch_cpp`, sigma, perm)
}

pmvn_fun_create_cpp <- function(lower, mean, sigma, upper_seed = NULL, n_points = 1021L, n_shifts = 8L, seed = 1L) {
    .Call(`_admvn_pmvn_fun_create_cpp`, lower, mean, sigma, upper_seed, n_points, n_shifts, seed)
}

pmvn_fun_perm_cpp <- function(ptr) {
    .Call(`_admvn_pmvn_fun_perm_cpp`, ptr)
}

pmvn_fun_eval_cpp <- function(ptr, upper, mean = NULL, sigma = NULL, inner = TRUE) {
    .Call(`_admvn_pmvn_fun_eval_cpp`, ptr, upper, mean, sigma, inner)
}

pmvn_domain_grad_cpp <- function(upper, mean, scale, ch, lower = NULL) {
    .Call(`_admvn_pmvn_domain_grad_cpp`, upper, mean, scale, ch, lower)
}

dsun_cpp <- function(x, par, log_scale = TRUE, deriv = 0L, n_points = 1021L, n_shifts = 8L, seed = 1L, n_threads = 1L, weights = NULL) {
    .Call(`_admvn_dsun_cpp`, x, par, log_scale, deriv, n_points, n_shifts, seed, n_threads, weights)
}

dsun_fun_create_cpp <- function(x, par_seed, n_points = 1021L, n_shifts = 8L, seed = 1L, n_threads = 1L, weights = NULL) {
    .Call(`_admvn_dsun_fun_create_cpp`, x, par_seed, n_points, n_shifts, seed, n_threads, weights)
}

dsun_fun_eval_cpp <- function(ptr, par = NULL, log_scale = TRUE, deriv = 0L, n_threads = 0L) {
    .Call(`_admvn_dsun_fun_eval_cpp`, ptr, par, log_scale, deriv, n_threads)
}

dsun_hs_cpp <- function(x, par, log_scale = TRUE, deriv = 0L, n_points = 1021L, n_shifts = 8L, seed = 1L, n_threads = 1L, weights = NULL) {
    .Call(`_admvn_dsun_hs_cpp`, x, par, log_scale, deriv, n_points, n_shifts, seed, n_threads, weights)
}

dsun_hs_fun_create_cpp <- function(x, par_seed, n_points = 1021L, n_shifts = 8L, seed = 1L, n_threads = 1L, weights = NULL) {
    .Call(`_admvn_dsun_hs_fun_create_cpp`, x, par_seed, n_points, n_shifts, seed, n_threads, weights)
}

dsun_n_threads_default_cpp <- function() {
    .Call(`_admvn_dsun_n_threads_default_cpp`)
}

dsun22_cpp <- function(x, par, log_scale = TRUE, deriv = 0L, n_points = 1021L, n_shifts = 8L, seed = 1L, n_threads = 1L, weights = NULL) {
    .Call(`_admvn_dsun22_cpp`, x, par, log_scale, deriv, n_points, n_shifts, seed, n_threads, weights)
}

dsun22_hs_cpp <- function(x, par, log_scale = TRUE, deriv = 0L, n_points = 1021L, n_shifts = 8L, seed = 1L, n_threads = 1L, weights = NULL) {
    .Call(`_admvn_dsun22_hs_cpp`, x, par, log_scale, deriv, n_points, n_shifts, seed, n_threads, weights)
}

dsun22_fun_create_cpp <- function(x, par_seed, n_points = 1021L, n_shifts = 8L, seed = 1L, n_threads = 1L, weights = NULL) {
    .Call(`_admvn_dsun22_fun_create_cpp`, x, par_seed, n_points, n_shifts, seed, n_threads, weights)
}

dsun22_hs_fun_create_cpp <- function(x, par_seed, n_points = 1021L, n_shifts = 8L, seed = 1L, n_threads = 1L, weights = NULL) {
    .Call(`_admvn_dsun22_hs_fun_create_cpp`, x, par_seed, n_points, n_shifts, seed, n_threads, weights)
}

dsun22_fun_eval_cpp <- function(ptr, par = NULL, log_scale = TRUE, deriv = 0L, n_threads = 0L) {
    .Call(`_admvn_dsun22_fun_eval_cpp`, ptr, par, log_scale, deriv, n_threads)
}

dsun44_cpp <- function(x, par, log_scale = TRUE, deriv = 0L, n_points = 1021L, n_shifts = 8L, seed = 1L, n_threads = 1L, weights = NULL) {
    .Call(`_admvn_dsun44_cpp`, x, par, log_scale, deriv, n_points, n_shifts, seed, n_threads, weights)
}

dsun44_hs_cpp <- function(x, par, log_scale = TRUE, deriv = 0L, n_points = 1021L, n_shifts = 8L, seed = 1L, n_threads = 1L, weights = NULL) {
    .Call(`_admvn_dsun44_hs_cpp`, x, par, log_scale, deriv, n_points, n_shifts, seed, n_threads, weights)
}

dsun44_fun_create_cpp <- function(x, par_seed, n_points = 1021L, n_shifts = 8L, seed = 1L, n_threads = 1L, weights = NULL) {
    .Call(`_admvn_dsun44_fun_create_cpp`, x, par_seed, n_points, n_shifts, seed, n_threads, weights)
}

dsun44_hs_fun_create_cpp <- function(x, par_seed, n_points = 1021L, n_shifts = 8L, seed = 1L, n_threads = 1L, weights = NULL) {
    .Call(`_admvn_dsun44_hs_fun_create_cpp`, x, par_seed, n_points, n_shifts, seed, n_threads, weights)
}

dsun44_fun_eval_cpp <- function(ptr, par = NULL, log_scale = TRUE, deriv = 0L, n_threads = 0L) {
    .Call(`_admvn_dsun44_fun_eval_cpp`, ptr, par, log_scale, deriv, n_threads)
}

sun_mle_cpp <- function(ptr, start, control, n_threads = 0L) {
    .Call(`_admvn_sun_mle_cpp`, ptr, start, control, n_threads)
}

