# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pmvn_cpp <- function(upper, lower, mean, sigma, n_points = 1021L, n_shifts = 8L, seed = 1L) {
    .Call(`_admvn_pmvn_cpp`, upper, lower, mean, sigma, n_points, n_shifts, seed)
}

pmvn_fun_create_cpp <- function(lower, mean, sigma, n_points = 1021L, n_shifts = 8L, seed = 1L) {
    .Call(`_admvn_pmvn_fun_create_cpp`, lower, mean, sigma, n_points, n_shifts, seed)
}

pmvn_fun_eval_cpp <- function(ptr, upper) {
    .Call(`_admvn_pmvn_fun_eval_cpp`, ptr, upper)
}

