# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Build raw AD handle for a random_fem_2 term (ssq + det shards)
#'
#' @param model An \code{ad_data} S4 object with FEM precision payload.
#' @param config Model configuration list.
#' @return External pointer of class \code{ad_fun_ptr} with two shards.
#' @keywords internal
#' @noRd
create_ad_fun_random_fem_2 <- function(model, config) {
    .Call(`_adlaplaceGrf_create_ad_fun_random_fem_2`, model, config)
}

#' Build raw AD handle for a random_fem_3 term (ssq + det shards)
#'
#' @param model An \code{ad_data} S4 object with FEM precision payload.
#' @param config Model configuration list.
#' @return External pointer of class \code{ad_fun_ptr} with two shards.
#' @keywords internal
#' @noRd
create_ad_fun_random_fem_3 <- function(model, config) {
    .Call(`_adlaplaceGrf_create_ad_fun_random_fem_3`, model, config)
}

