// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getAdFun
SEXP getAdFun(Rcpp::List data, Rcpp::List config, const bool inner);
RcppExport SEXP _hpolcc_getAdFun(SEXP dataSEXP, SEXP configSEXP, SEXP innerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type config(configSEXP);
    Rcpp::traits::input_parameter< const bool >::type inner(innerSEXP);
    rcpp_result_gen = Rcpp::wrap(getAdFun(data, config, inner));
    return rcpp_result_gen;
END_RCPP
}
// jointLogDensNoAdfun
double jointLogDensNoAdfun(Rcpp::NumericVector parameters, Rcpp::List data, Rcpp::List config);
RcppExport SEXP _hpolcc_jointLogDensNoAdfun(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(jointLogDensNoAdfun(parameters, data, config));
    return rcpp_result_gen;
END_RCPP
}
// jointLogDens
double jointLogDens(Rcpp::NumericVector parameters, SEXP adPack, Rcpp::List config);
RcppExport SEXP _hpolcc_jointLogDens(SEXP parametersSEXP, SEXP adPackSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< SEXP >::type adPack(adPackSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(jointLogDens(parameters, adPack, config));
    return rcpp_result_gen;
END_RCPP
}
// grad
Rcpp::NumericVector grad(Rcpp::NumericVector parameters, SEXP adPack, Rcpp::List config);
RcppExport SEXP _hpolcc_grad(SEXP parametersSEXP, SEXP adPackSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< SEXP >::type adPack(adPackSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(grad(parameters, adPack, config));
    return rcpp_result_gen;
END_RCPP
}
// hessian
Rcpp::S4 hessian(Rcpp::NumericVector parameters, SEXP adPack, Rcpp::List config);
RcppExport SEXP _hpolcc_hessian(SEXP parametersSEXP, SEXP adPackSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< SEXP >::type adPack(adPackSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(hessian(parameters, adPack, config));
    return rcpp_result_gen;
END_RCPP
}
// inner_opt
Rcpp::List inner_opt(Rcpp::NumericVector parameters, Rcpp::List data, Rcpp::List control, Rcpp::List config);
RcppExport SEXP _hpolcc_inner_opt(SEXP parametersSEXP, SEXP dataSEXP, SEXP controlSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(inner_opt(parameters, data, control, config));
    return rcpp_result_gen;
END_RCPP
}
// inner_opt_adpack
Rcpp::List inner_opt_adpack(Rcpp::NumericVector parameters, SEXP adPack, const Rcpp::List control, const Rcpp::List config);
RcppExport SEXP _hpolcc_inner_opt_adpack(SEXP parametersSEXP, SEXP adPackSEXP, SEXP controlSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< SEXP >::type adPack(adPackSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(inner_opt_adpack(parameters, adPack, control, config));
    return rcpp_result_gen;
END_RCPP
}
// traceHinvT
Rcpp::NumericVector traceHinvT(const Rcpp::NumericVector parameters, const Rcpp::S4& LinvPt, const Rcpp::S4& LinvPtColumns, const Rcpp::List config, SEXP adPack);
RcppExport SEXP _hpolcc_traceHinvT(SEXP parametersSEXP, SEXP LinvPtSEXP, SEXP LinvPtColumnsSEXP, SEXP configSEXP, SEXP adPackSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::S4& >::type LinvPt(LinvPtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::S4& >::type LinvPtColumns(LinvPtColumnsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type config(configSEXP);
    Rcpp::traits::input_parameter< SEXP >::type adPack(adPackSEXP);
    rcpp_result_gen = Rcpp::wrap(traceHinvT(parameters, LinvPt, LinvPtColumns, config, adPack));
    return rcpp_result_gen;
END_RCPP
}
// sparsity
Rcpp::List sparsity(Rcpp::List data, Rcpp::List config);
RcppExport SEXP _hpolcc_sparsity(SEXP dataSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(sparsity(data, config));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hpolcc_getAdFun", (DL_FUNC) &_hpolcc_getAdFun, 3},
    {"_hpolcc_jointLogDensNoAdfun", (DL_FUNC) &_hpolcc_jointLogDensNoAdfun, 3},
    {"_hpolcc_jointLogDens", (DL_FUNC) &_hpolcc_jointLogDens, 3},
    {"_hpolcc_grad", (DL_FUNC) &_hpolcc_grad, 3},
    {"_hpolcc_hessian", (DL_FUNC) &_hpolcc_hessian, 3},
    {"_hpolcc_inner_opt", (DL_FUNC) &_hpolcc_inner_opt, 4},
    {"_hpolcc_inner_opt_adpack", (DL_FUNC) &_hpolcc_inner_opt_adpack, 4},
    {"_hpolcc_traceHinvT", (DL_FUNC) &_hpolcc_traceHinvT, 5},
    {"_hpolcc_sparsity", (DL_FUNC) &_hpolcc_sparsity, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_hpolcc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
