```{r setup, include=FALSE}
#devtools::install_github("samperochkin/hpoltest")
```

```{r indiaDataAlex}
load("/home/patrick/research/hpoltest/applications/india/combinedindianmorttempdata_meannofilter.Rdata")
x = indianmorttempdata

table(x$death_cause, x$case)
quantile(x$final_temp)
tempSdByStrata = tapply(x$final_temp, x$riskset, sd)
countByStrata = tapply(x$case, x$riskset, sum)
# nuber cases per day
table(tapply(x$case, x$date, sum))


tempRef = 32

x$tempHigh = pmax(x$final_temp - tempRef, 0)
x$tempLow = pmin(x$final_temp - tempRef, 0)

x$tempC = x$final_temp - tempRef
x$tempSq = (x$final_temp - tempRef)^2
x$temp3 = (x$final_temp - tempRef)^3

x$dateInt = as.integer(x$date)

xSub = x[x$death_cause == 'stroke', ]
Slow = unique(unlist(xSub[xSub$final_temp < 10, 'riskset']))

Shigh = unique(unlist(xSub[xSub$final_temp >37, 'riskset']))



xSub2 = xSub[! xSub$riskset %in% c(Slow, Shigh), ]

library('survival')
fitClogit = clogit(case ~ tempHigh + tempLow + strata(riskset),
       data = x[x$death_cause == 'stroke',])
summary(fitClogit)$coef


#library('hpoltest')
fitLinear <- hnlm(
  formula = case ~  tempHigh + tempLow + f(dateInt, model='iid'),
  cc_design = ccDesign(strat_vars = c('riskset')),
  tmb_parameters = list(theta = 20, map = list(theta=factor(NA))),
  data = xSub2,
  verbose=FALSE
  )

fitLinear$est$param$est

randomDate = as.Date(
  as.integer(gsub("factor.dateInt.", "", names(fitLinear$est$random$est))),
  as.integer(as.Date('1970/1/1')))
  
badDates = randomDate[order(abs(fitLinear$est$random$est), decreasing=TRUE)[1:2]]
stuff = as.data.frame(xSub[xSub$date %in% badDates, c('riskset', 'date','final_temp','case')])
stuff = stuff[order(stuff$date,stuff$riskset), ]
stuff


plot(randomDate, fitLinear$est$random$est)

fitLinear2 <- hnlm(
  formula = case ~  tempHigh + tempLow + f(dateInt, model='iid'),
  cc_design = ccDesign(strat_vars = c('riskset')),
  data = xSub2,
  verbose=FALSE
  )

fitLinear$est$param$est
fitLinear2$est$param$est


fitQuad  <- hnlm(
  formula = case ~  tempC + tempSq + temp3 + f(dateInt, model='iid'),
  cc_design = ccDesign(strat_vars = c('riskset')),
  tmb_parameters = list(theta = -5, map = list(theta=factor(NA))),
  data = xSub2,
  verbose=FALSE
  )
fitLinear$est$param$est
fitLinear2$est$param$est
fitQuad$est$param$est
```

```{r comparePlots}
tempSeq = seq(10, 40)
tempSeqC = tempSeq - tempRef

plot(tempSeq,
     tempSeqC*fitQuad$est$param$est['tempC'] + 
     tempSeqC^2*fitQuad$est$param$est['tempSq'] +
     tempSeqC^3*fitQuad$est$param$est['temp3'],
     type='l'
)
lines(tempSeq,
      pmin(tempSeqC, 0) * fitClogit$coef['tempLow'] + 
      pmax(tempSeqC, 0) * fitClogit$coef['tempHigh'],
      col='green', lwd=3, lty=1
)
lines(tempSeq,
      pmin(tempSeqC, 0) * fitLinear$est$param$est['tempLow'] + 
      pmax(tempSeqC, 0) * fitLinear$est$param$est['tempHigh'],
      col='red', lwd=3, lty=2
)
lines(tempSeq,
      pmin(tempSeqC, 0) * fitLinear2$est$param$est['tempLow'] + 
      pmax(tempSeqC, 0) * fitLinear2$est$param$est['tempHigh'],
      col='orange', lwd=3, lty=2
)

legend('bottomleft', bty='n', lty=1, col=c('black','red','orange','green'),
       legend = c('cubic', 'linear no OD','linear','clogit'))

```

```{r fitSimple, include=FALSE}
tempKnots = seq(0,40, by=0.5)
fitSimple <- hnlm(
  formula = case ~  f(final_temp, model='iwp', ref_value = tempRef, p=4, knots = tempKnots) + 
    f(dateInt, model='iid'),
  cc_design = ccDesign(strat_vars = c('riskset')),
  tmb_parameters = list(theta = c(-1,-5), map = list(theta=factor(c(NA,1)))),
  data = xSub2,
  verbose=FALSE
  )

fitSimple$est$param$est 
fitQuad$est$param$est
```



```{r plotIwp}
fit = fitSimple

thetaHat = fit$est$param$est[grep("theta", names(fit$est$param$est))]
(thetaSd = exp(-thetaHat/2))

betaHat = fit$est$param$est[grep("theta", names(fit$est$param$est), invert=TRUE)]
names(betaHat) = colnames(fit$obj$env$.data$X)
betaHat


Dterm = 'final_temp'


Nsim = 500

# approx gamma | Y ~ N(gamma hat, hessian^(-1))
randomMean = fit$est$random$est
precMat = Matrix::forceSymmetric(fit$est$random$hessian)
#cholPrecMat = chol(precMat)
#randomVcovChol = solve(cholPrecMat)

Shere = grep(Dterm, names(randomMean))
cholSchur = chol(rje::schur(as.matrix(precMat), Shere, Shere, setdiff(1:length(randomMean), Shere)))
cholSchurInv = solve(cholSchur)

gammaSim = cholSchurInv %*% matrix(rnorm(Nsim*nrow(cholSchur)), ncol=Nsim,
                                     dimnames = list(rownames(cholSchur), 1:Nsim))


#gammaSim = randomVcovChol %*% matrix(rnorm(Nsim*length(randomMean)), ncol=Nsim,
#                                     dimnames = list(names(randomMean), 1:Nsim))


df = data.frame(x = seq(10, 40,by=0.1))
names(df) = gsub("^x$", Dterm, names(df))
newXA = hpoltest:::getNewXA(fit$terms, df)

parametricPart = newXA$X[,grep(Dterm, colnames(newXA$X)),drop=FALSE] %*% 
  betaHat[grep(Dterm, names(betaHat)),drop=FALSE]
iwpConstr = newXA$A %*% gammaSim[colnames(newXA$A), ]


iwpSim = parametricPart + iwpConstr
matplot(df[[Dterm]], 
        t(apply(iwpSim, 1, quantile, prob = c(0.025, 0.5, 0.975))), 
        type='l', col='black', lty=1, xaxs='i',
        ylim = c(-1,2))

lines(tempSeq,
     tempSeqC*fitQuad$est$param$est['tempC'] + 
     tempSeqC^2*fitQuad$est$param$est['tempSq'] +
     tempSeqC^3*fitQuad$est$param$est['temp3'],
     col='yellow'
)
lines(tempSeq,
      pmin(tempSeqC, 0) * fitClogit$coef['tempLow'] + 
      pmax(tempSeqC, 0) * fitClogit$coef['tempHigh'],
      col='green', lwd=3, lty=1
)
lines(tempSeq,
      pmin(tempSeqC, 0) * fitLinear$est$param$est['tempLow'] + 
      pmax(tempSeqC, 0) * fitLinear$est$param$est['tempHigh'],
      col='red', lwd=3, lty=2
)
lines(tempSeq,
      pmin(tempSeqC, 0) * fitLinear2$est$param$est['tempLow'] + 
      pmax(tempSeqC, 0) * fitLinear2$est$param$est['tempHigh'],
      col='orange', lwd=3, lty=2
)

legend('bottomleft', bty='n', lty=1, col=c('black','yellow','red','orange','green'),
       legend = c('iwp','cubic', 'linear no OD','linear','clogit'))

```



```{r fitTemperatureAlex, include=FALSE, eval=FALSE}

tempKnots = seq(-5,40,by=2.5)
library('hpoltest')
fitAsAlex <- hnlm(
  case ~  f(final_temp, model='iwp', ref_value = 30, p=2, knots = tempKnots),
  cc_design = ccDesign(strat_vars = c('riskset')),
  data = x[x$death_cause == 'stroke',],
  verbose=FALSE
  )
fitIwp3NoOd <- hnlm(
  case ~  f(final_temp, model='iwp', ref_value = 30, p=3, knots = tempKnots),
  cc_design = ccDesign(strat_vars = c('riskset')),
  data = x[x$death_cause == 'stroke',],
  verbose=FALSE
  )

fitIwp3 <- hnlm(
  case ~  f(final_temp, model='iwp', ref_value = 30, p=3, knots = tempKnots) +
     f(date, model='iid'),
  cc_design = ccDesign(strat_vars = c('riskset')),
  data = x[x$death_cause == 'stroke',],
  optim_parameters = list(eval.max=1e4, iter.max=1e4, trace=FALSE),
  inner.control = list(maxit = 1e4, tol10=1e-4, tol=1e-9, ustep=0.5),
  verbose=FALSE
  )
fitIwp2 <- hnlm(
  case ~  f(final_temp, model='iwp', ref_value = 30, p=2, knots = tempKnots) +
     f(date, model='iid'),
  cc_design = ccDesign(strat_vars = c('riskset')),
  data = x[x$death_cause == 'stroke',],
  verbose=FALSE
  )
fitAsAlex <- hnlm(
  case ~  f(final_temp, model='iwp', ref_value = 30, p=2, knots = tempKnots),
  cc_design = ccDesign(strat_vars = c('riskset')),
  data = x[x$death_cause == 'stroke',],
  verbose=FALSE
  )
```


```{r setup2}
removeUnusedStrata = function(x, Sstrata, outcome, NeventCutoff = 0) {
  # Convert to data.table if not already
  if (!data.table::is.data.table(x)) {
    x <- data.table::as.data.table(x)
  }
  
  # Calculate summary statistics by strata
  NinStrata <- x[, .(Ndays = .N, Nevents = sum(get(outcome[1]))), by = Sstrata]
  
  # Filter strata meeting criteria
  NinStrata <- NinStrata[Ndays > 1 & Nevents > NeventCutoff]
  
  # Merge back with original data
  xout <- x[NinStrata, on = Sstrata, nomatch = 0]
  
  # Add required columns and attributes
  xout[, y := get(outcome[1])]
  data.table::setattr(xout, "strata", Sstrata)
  data.table::setattr(xout, "outcome", outcome[1])
  
  return(xout)
}


Sstrata = c("cell","ecoRegion", "yearWeek3Dow")
pmKnots = c(0,1, 2, 5, 7,  10, 15, 20, 25) # on square root scale
tempKnots = c(-15, -5,  5, 10, 13, seq(25,35, by=2), 37, 39)

outcome = 'medical'


library('data.table')
# /home/patrick/Admin/globalHealth/indiaSpatial/daily.Rmd
SstoreDir = c('/store/patrick/copernicus/agg', '~/Downloads')
storeDir = SstoreDir[1]
if(!dir.exists(storeDir)) storeDir = SstoreDir[2]

deaths = as.data.table(readRDS( file.path(storeDir, "indiaCC.rds")))

indiaEcoRegions = terra::unwrap(readRDS(file.path(storeDir, "indiaEcoRegions.rds")))


# trransform variables
deaths$sqrtPm = sqrt(pmin(deaths$pm,1000))
deaths$timeIid = as.numeric(deaths$date)

deaths$tempClean = pmax(deaths$temp, -15)

theMax = which.max(deaths$medical)
whichIsTheMax = which(deaths$yearMonthDow == unlist(deaths[theMax, 'yearMonthDow']) &
  deaths$cell == unlist(deaths[theMax, 'cell']))

deaths[whichIsTheMax,]
deaths = deaths[-whichIsTheMax, ]

deaths$dom = as.numeric(format(deaths$date, '%d'))
deaths[deaths$dom == Hmisc::monthDays(deaths$date), 'dom'] = 31
deaths[format(deaths$date, '%m%d') == '0101', 'dom'] = 0
deaths$dom = relevel(factor(deaths$dom), '1')
deaths$month = format(deaths$date, '%m')


quantile(deaths$sqrtPm)
quantile(deaths$tempClean)
```






```{r digitPreference}
checkForDigitPreference1 = aggregate(deaths[,'medical', drop=FALSE],
  deaths[,c('dom','month')], sum)
checkForDigitPreference = dcast(as.data.table(checkForDigitPreference1), dom ~ month)
image(as.numeric(checkForDigitPreference$dom),
 as.numeric(colnames(checkForDigitPreference)[-1]),
  as.matrix(checkForDigitPreference[,-1]))
```


```{r fit}
# devtools::install_github("samperochkin/hpoltest")
#devtools::load_all("~/research/hpoltest")
library("hpoltest")

dataMedSimple = removeUnusedStrata(
  deaths[
    deaths$date >= as.Date('2006/1/1') &
    format(deaths$date, '%b%d') != 'Jan01' &
    !deaths$ecoRegion %in% c(7, 8,10), ],
  Sstrata, outcome)
formulaMedSimple <- y ~ f(date, model='iid') +
    f(temp, model='iwp',ref_value = 25, p=3, knots = seq(-40,45,by=2.5))

devtools::load_all("~/research/hpoltest")
fit<- hnlm(
  formula=formulaMedSimple, 
  data=dataMedSimple,
#  tmb_parameters = list(theta = c(5.25,31)),
  cc_design =  c("cell",  "ecoRegion", "yearWeek3Dow"),
  dirichelet=TRUE,
#  optim_parameters = list(eval.max=1e4, iter.max=1e4, trace=1),
#  inner.control = list(maxit = 1e4, tol10=1e-4, tol=1e-9, ustep=0.5, intern=TRUE),
  verbose=TRUE, for_dev=TRUE 
  )
attach(fit)
 r <- if(length(tmb_parameters$gamma) > 0){"gamma"}else{NULL}
  obj <- MakeADFun(data = tmb_data,
                   parameters = tmb_parameters[c('beta','gamma','theta')],
                   random = r,
                   map = map,
                   intern=FALSE, type='ADFun',
                   DLL = "hpoltest")
  obj$fn(obj$par)

  obj$fn(c(0,0,4,4,0.3))
  obj$fn(c(0,0,4,4,0.01))
  obj$fn(c(0,0,4,4,0))

  
dataMedSimplePm = removeUnusedStrata(
  deaths[
    deaths$date >= as.Date('2006/1/1') &
    format(deaths$date, '%b%d') != 'Jan01' &
    !deaths$ecoRegion %in% c(7, 8,10), ],
  Sstrata, outcome)
formulaMedSimplePm <- y ~ dom + f(date, model='iid') +
    f(sqrtPm, model='iwp',ref_value = 25, p=3, knots = pmKnots)

fitPm<- hnlm(
  formula=formulaMedSimplePm, 
  data=dataMedSimplePm,
#  tmb_parameters = list(theta = c(5.25,31)),
  cc_design =  ccDesign(strat_vars = Sstrata),
  optim_parameters = list(eval.max=1e4, iter.max=1e4, trace=1),
  inner.control = list(maxit = 1e4, tol10=1e-4, tol=1e-9, ustep=0.5, intern=TRUE),
  verbose=TRUE, for_dev=FALSE 
  )

#  f(sqrtPm, model='hiwp', ref_value = 7, p=2, knots = pmKnots, group_var = ecoRegion) 
#  f(tempClean, model='hiwp',ref_value = 25, p=3, knots = tempKnots, group_var = ecoRegion)

formulaCvd = cvd ~ dom + f(date, model='iid') + f(tempClean, model='hiwp',ref_value = 25, p=3, knots = tempKnots, group_var = ecoRegion)

formulaMedSenior <- medical_senior ~ dom + f(date, model='iid') +
    f(tempClean, model='hiwp',ref_value = 25, p=3, knots = tempKnots, group_var=ecoRegion)
#  f(sqrtPm, model='hiwp', ref_value = 7, p=2, knots = pmKnots, group_var = ecoRegion) 


formulaCvdSimple = cvd ~ dom + f(date, model='iid') + 
  f(sqrtPm, model='hiwp', ref_value = 7, p=2, knots = pmKnots, group_var = ecoRegion) 
#f(tempClean, model='iwp',ref_value = 25, p=3, knots = tempKnots)

formulaMedSeniorSimple = medical_senior ~ dom + f(date, model='iid') + 
  f(tempClean, model='iwp',ref_value = 25, p=3, knots = tempKnots)

    dataMed = deaths[which(deaths$N_Week3_medical > 0 & deaths$date > as.Date('2009/1/1')),]

        dataMedSenior = deaths[which(deaths$N_Week3_medical_senior > 0 & 
                                   deaths$date > as.Date('2006/1/1')),]
dataCvd = deaths[which(deaths$N_Week3_cvd > 0 & deaths$date > as.Date('2006/1/1')), ]

if(FALSE) {

fitMedSeniorSimple = hnlm(formulaMedSeniorSimple, dataMedSenior, cc_design, 
                            optim_parameters = list(eval.max=1e4, iter.max=1e4, trace=1),
  inner.control = list(maxit = 1e4, tol10=1e-4, tol=1e-9, ustep=0.5, intern=TRUE),
                          verbose=TRUE)

fitCvdSimple<- hnlm(
  formula=formulaCvdSimple, 
  data=dataCvd,
#  tmb_parameters = list(theta = c(5.25,31)),
  cc_design = cc_design,
  optim_parameters = list(eval.max=1e4, iter.max=1e4, trace=1),
  inner.control = list(maxit = 1e4, tol10=1e-4, tol=1e-9, ustep=0.5, intern=TRUE),
  verbose=TRUE, for_dev=FALSE 
  )
saveRDS(fitCvdSimple, file.path(storeDir, 'cvdSimple.rds'))

fitCvdSetup <- hnlm(
  formula=formulaCvd, 
  data=dataCvd,
  cc_design = cc_design,
  verbose=TRUE, for_dev=TRUE 
  )

fitCvdSetup$tmb_parameters$beta = fitCvdSimple$est$param$est[1:length(fitCvdSetup$tmb_parameters$beta)]
thetaHat = fitCvdSimple$est$param$est[grep("theta", names(fitCvdSimple$est$param$est))]

fitCvdSetup$tmb_parameters$theta[1:length(thetaHat)] = thetaHat
fitCvdSetup$tmb_parameters$theta[-(1:length(thetaHat))] = 0
fitCvdSetup$tmb_parameters$gamma[1:length(fitCvdSimple$est$random$est)] = fitCvdSimple$est$random$est

  obj <- MakeADFun(data = fitCvdSetup$tmb_data,
                   parameters = fitCvdSetup$tmb_parameters,
#                   random = 'gamma',
                   map = list(
                    beta = factor(rep(NA, length(fitCvdSetup$tmb_parameters$beta))),
                    theta=factor(rep(NA, length(fitCvdSetup$map$theta)))),
                   intern=FALSE, type='ADFun',
                   DLL = "hpoltest")

  parCat = rep(NA, ncol(obj$env$.data$A))
  parCat[grep("date", colnames(obj$env$.data$A))]='date'
  parCat[grep("hrpoly", colnames(obj$env$.data$A))]='poly'
  parCat[grep("hiwp", colnames(obj$env$.data$A))]='hiwp'
  parCat[grep("global", colnames(obj$env$.data$A))]='global'

  the19 = grep('hiwp_19', colnames(obj$env$.data$A), value=TRUE)

  obj$fn(obj$par)
    opt <- optim(
      par = rnorm(length(obj$par), obj$par, 1e-2),
      fn = obj$fn, 
      gr = obj$gr,
      method = 'BFGS',
      control = list(
        trace=TRUE, 
        maxit=1e5,
        parscale = c(date=1,global=1e-5, hiwp=1e-2, poly=1e-2)[parCat]
    )
  )


            names(opt$par) = colnames(obj$env$.data$A)

                opt$par1 = opt$par[grep("date", names(opt$par))]
    opt$par2 = opt$par[!names(opt$par)%in% names(opt$par1)]

    quantile(obj$gr(opt$par))

        
fitMedSenior <- hnlm( 
  formula=formulaMedSenior, data=dataMedSenior, #[which(deaths$date > as.Date('2009/1/1')), ], 
  cc_design = cc_design,verbose=TRUE, for_dev=FALSE,
    optim_parameters = list(eval.max=1e4, iter.max=1e4),
  inner.control = list(maxit = 1e4, tol10=1e-4, tol=1e-9, ustep=0.5, intern=TRUE)
  )


  obj <- MakeADFun(data = fitMed1$tmb_data,
                   parameters = fitMed1$tmb_parameters[c('beta','gamma','theta')],
                   random = 'gamma',
                   map = fitMed1$map,
                   intern=FALSE, type='ADFun',
                   DLL = "hpoltest")
  obj$fn(obj$par)
    opt <- optim(par = obj$par, 
      fn = obj$fn, gr = obj$gr,
      control = list(trace=TRUE)
  )
saveRDS(fitMed, file.path(storeDir, 'ccMed.rds'))
fitCvd <- hnlm(
  formula=formulaCvd, 
  data=dataCvd,
  cc_design = cc_design,
#  optim_parameters = list(eval.max=100, iter.max=5),
  verbose=TRUE, for_dev=FALSE 
  )
saveRDS(fitCvd, file.path(storeDir, 'ccCvd.rds'))
}
fitCvd = readRDS(file.path(storeDir, 'ccCvd.rds'))
```

```{r temperatureDataFromIndia}
deathsTemp = as.data.table(readRDS( file.path(storeDir, "indiaTemperature.rds")))
deathsTemp$dom = as.numeric(format(deathsTemp$date, '%d'))
deathsTemp[deathsTemp$dom == Hmisc::monthDays(deathsTemp$date), 'dom'] = 31
deathsTemp[format(deathsTemp$date, '%m%d') == '0101', 'dom'] = 0
deathsTemp$dom = relevel(factor(deathsTemp$dom), '1')
deathsTemp$month = format(deathsTemp$date, '%m')


(theEtable = sort(table(deathsTemp$ecoRegion), decreasing=TRUE))
# 10, 17, 20 looks dodgy



Sstrata = c("cell","ecoRegion", "yearWeek3Dow")
knotsTemperature = seq(0,50, by=2.5)  

outcome = 'medical'

deathsTempMed = removeUnusedStrata(deathsTemp[
  deathsTemp$date >= as.Date('2006/1/1') &
  format(deathsTemp$date, '%b%d') != 'Jan01', ],
  Sstrata, outcome)


deathsTempMed$tempCut = 2*round(deathsTempMed$maxtemp/2)
ttable1 = dcast(deathsTempMed, tempCut ~ ecoRegion, value.var=outcome, fun.aggregate=sum)
ttable2 = dcast(deathsTempMed, tempCut ~ ecoRegion, value.var=outcome, fun.aggregate=length)

matplot(ttable1[,1], as.matrix(ttable1[,-1]/ttable2[,-1])[,names(theEtable)[10+1:9]])
merge(
  deathsTempMed, 
    as.data.frame(deathsTempMed)[order(deathsTempMed$y, decreasing=TRUE)[1:3], Sstrata],
    all.x=FALSE, all.y=TRUE)

deathsTempMed$tempLow = pmin(25, deathsTempMed$maxtempLag01)
deathsTempMed$tempHigh = pmax(25, deathsTempMed$maxtempLag01)

SexcludeRegions  = c(7, 10,13)
SincludeRegions = c(1:6, 8,9)
library(hpoltest)
fit <- hnlm(
  formula= y ~  dom + 
    f(date, model='iid') +
    f(maxtempLag01, model='hiwp',ref_value = 25, p=3, knots = knotsTemperature, group_var=ecoRegion),
  data=deathsTempMed[deathsTempMed$ecoRegion %in% SincludeRegions,],
  cc_design = ccDesign(strat_vars = Sstrata),
  optimizer='optim',
  optim_parameters = list(
    method = 'BFGS',
    maxit=1e5, eval.max=1e4, iter.max=1e4),
  inner.control = list(
    smartsearch=FALSE, 
    maxit = 1e4, tol10=1e-4, tol=1e-9, ustep=0.5, intern=TRUE),
  verbose=TRUE)



formulaMedSeniorIwp = medical_senior ~ dom + f(date, model='iid') + 
  f(maxtemp, model='iwp',ref_value = 25, p=3, knots = knotsTemperature)
<<<<<<< HEAD
formulaMedIwp = medical ~  #f(date, model='iid') + 
  f(maxtemp, model='iwp',ref_value = 25, p=3, knots = knotsTemperature)
=======
>>>>>>> 5cd10894fd1efbce224e23e3a8e7001c616db32c

fitTempMedSeniorIwp <- hnlm(
  formula=formulaMedSeniorIwp, 
  data=deathsTempSeniorMed3,
  cc_design = ccDesign(strat_vars = c("cell","ecoRegion", "yearWeek3Dow")),
  optimizer='optim',
  optim_parameters = list(
    method = 'BFGS',
    maxit=1e5, eval.max=1e4, iter.max=1e4),
  inner.control = list(
    maxit = 1e4, tol10=1e-4, tol=1e-9, ustep=0.5, intern=TRUE),
  verbose=TRUE)

fitTempMedIwp <- hnlm(
  formula=formulaMedIwp, 
  data=deathsTempMed,
  cc_design = ccDesign(strat_vars = Sstrata),
  optimizer='optim',
  optim_parameters = list(
    method = 'BFGS',
    maxit=1e5, eval.max=1e4, iter.max=1e4),
  inner.control = list(
    maxit = 1e4, tol10=1e-4, tol=1e-9, ustep=0.5, intern=TRUE),
  verbose=TRUE)
```


```
# darjeeling
# INTEL oneMKL ERROR: /usr/lib/x86_64-linux-gnu/libmkl_core.so.2: cannot open shared object file: No such file or directory.
sudo ln -s /opt/intel/oneapi/mkl/latest/lib/libmkl_core.so.2  /usr/lib/x86_64-linux-gnu/libmkl_core.so.2
sudo ln -s /opt/intel/oneapi/mkl/latest/lib/libmkl_gnu_thread.so.2  /usr/lib/x86_64-linux-gnu/libmkl_gnu_thread.so.2
sudo ln -s /opt/intel/oneapi/mkl/latest/lib/libmkl_tbb_thread.so.2  /usr/lib/x86_64-linux-gnu/libmkl_tbb_thread.so.2
sudo ln -s /opt/intel/oneapi/mkl/latest/lib/libmkl_intel_lp64.so.2 /lib/x86_64-linux-gnu/libmkl_intel_lp64.so.2
sudo ln -s /opt/intel/oneapi/mkl/latest/lib/libmkl_intel_lp64.so.2 /lib/x86_64-linux-gnu/libmkl_intel_lp64.so.2
sudo ln -s /opt/intel/oneapi/mkl/latest/lib/libmkl_def.so.2 /lib/x86_64-linux-gnu/libmkl_def.so.2
sudo ln -s /opt/intel/oneapi/mkl/latest/lib/libmkl_avx512.so.2 /lib/x86_64-linux-gnu/libmkl_avx512.so.2
```


```{r }
fit = readRDS(file.path(storeDir, 'ccCvd.rds'))

Dterm = 'tempClean'
#table(names(fit$obj$env$last.par.best))

Dterm = 'maxtempLag01'
  Nsim = 500


  thetaHat = fit$est$param$est[grep("theta", names(fit$est$param$est))]
  (thetaSd = exp(-thetaHat/2))

  betaHat = fit$est$param$est[grep("theta", names(fit$est$param$est), invert=TRUE)]
  names(betaHat) = colnames(fit$obj$env$.data$X)
  betaHat

  # approx gamma | Y ~ N(gamma hat, hessian^(-1))
  randomMean = fit$est$random$est

  randomVcovChol = solve(chol(Matrix::forceSymmetric(fit$est$random$hessian)))

  gammaSim = randomVcovChol %*% matrix(rnorm(Nsim*length(randomMean)), ncol=Nsim)

  df = data.frame(x = seq(5, 47), ecoRegion = NA)
  names(df) = gsub("^x$", Dterm, names(df))
  newXA = hpoltest:::getNewXA(fit$terms, df)

  parametricPart = newXA$X[,grep(Dterm, colnames(newXA$X)),drop=FALSE] %*% 
    betaHat[grep(Dterm, names(betaHat))]
  iwpConstr = newXA$A %*% gammaSim[seq(to=nrow(gammaSim), by=1, len=ncol(newXA$A)), ]


  iwpSim = parametricPart + iwpConstr
  matplot(df[[Dterm]], exp(iwpSim), type='l', col='#00000040', lty=1, xaxs='i', log='y')

dayEffect = randomMean[grep("factor.date", names(randomMean))]
dayEffect = data.frame(
  date = as.Date(gsub("factor.date.", "", names(dayEffect))),
  est = dayEffect
)

plot(dayEffect)

dayEffect[order(abs(dayEffect$est), decreasing=TRUE)[1:12], ]


iwpSimRegion = list()
for(D in unique(deaths$ecoRegion)) {
  df2 = data.frame(tempClean = seq(4, 41), ecoRegion = D)
  newXA2 = hpoltest:::getNewXA(fit$terms, df2)
  iwpSimRegion[[as.character(D)]] = newXA2$A %*% gammaSim[colnames(newXA$A), ]
}
iwpSimRegion = lapply(iwpSimRegion, as.matrix)
iwpSimRegion = do.call(abind::abind, c(iwpSimRegion, list(along=3)))
iwpSimRegionSum = apply(exp(iwpSimRegion), 1:2, mean)

matplot(df$tempClean, iwpSimRegionSum, type='l', col='#00000040', lty=1, xaxs='i', log='y')
matlines(df$tempClean, t(apply(iwpSimRegionSum,1,quantile, prob = c(0.025, 0.975, 0.5))), 
  col='blue', lty=c(2,2,1))


```



```{r}

fit = fitMed
tempEffect <- getEffect(fit, exposure_var = "tempClean", 
                     group_var = "ecoRegion", group = NA, 
                     values = seq(0,40),
                     ref_values = list(tempClean = 20))
pmEffect <- getEffect(fit, exposure_var = "sqrtPm", 
                     group_var = "ecoRegion", group = NA, 
                     values = seq(0,30),
                     ref_values = list(sqrtPm=5))

plot(pmEffect[,2:3])
plot(tempEffect[,2:3])

table(names(fit$obj$env$last.par.best))
fit$obj$env$last.par.best[grep("gamma", names(fit$obj$env$last.par.best), invert=TRUE)]



term = 'tempClean'
Nsim = 100

termInfo = do.call(rbind,
                   lapply(fit$terms, function(xx) unlist(xx[c('var','model')])))
termFpoly = which(termInfo[,'var'] == term & termInfo[,'model'] == 'fpoly')
termIwp = which(termInfo[,'var'] == term & grepl("iwp", termInfo[,'model']))

termRef = fit$terms[[termIwp]]$ref_value

termLims = quantile(fit$obj$env$data$X[,term], c(0,1), na.rm=TRUE) + termRef
termLims = c(5, 40)
newx = seq(termLims[1], termLims[2], len=1000)
newxRef = newx-termRef

newXmat = poly(newxRef, degree=fit$terms[[termFpoly]]$p)

parMle = fit$obj$env$last.par.best[
  grep("gamma", names(fit$obj$env$last.par.best), invert=TRUE)
  ]

betaHat = parMle[names(parMle) == 'beta']

parametricPart = newXmat %*%  betaHat

#plot(newx, parametricPart, type='l')

newxDf = data.frame(x = newx)
names(newxDf) = term
newDesign = getDesign(fit$terms[[termIwp]], newxDf)

# matplot(newx, newDesign,lty=1, type='l')

termId = grep(term, fit$gamma_info$var)
termMean = randomMean[termId]
termVcov = randomVcov[termId, termId]

termGammaSim = mvtnorm::rmvnorm(Nsim, termMean, as.matrix(termVcov))

iwpSimC = tcrossprod(newDesign, termGammaSim)
# matplot(newx, iwpSimC,lty=1, type='l')

iwpSim = iwpSimC + parametricPart


matplot(newx, iwpSim, type='l',lty=1, col='#00000030')



```




```{r resEffects, eval=FALSE}

estPm <- getEffect(fit, exposure_var = "tempClean",
                    group_var = "ecoRegionInt", 
                    group = c(1,2),
                    values = seq(-10, 30,by=1),
                    ref_values = list(tempClean=10))
plot(estPm[estPm$group == 10,c('var_value','effect_value')])

#report <- sdreport(fit$obj)
#randomMean = report$par.random

random2 = fit$obj$env$random

parMle = fit$obj$env$last.par.best[
  grep("gamma", names(fit$obj$env$last.par.best), invert=TRUE)
  ]

sdMle = 1/sqrt(exp(fit$obj$env$last.par.best[
  grep("theta", names(fit$obj$env$last.par.best))
  ]))

parAllMle = fit$obj$env$last.par.best
#parAllMle[grep("gamma", names(parAllMle))] = randomMean



newdata = data.frame(sqrtPm = seq(0, sqrt(200), len=200), ecoRegionInt = 'Global')

varInfo = do.call(rbind, lapply(fit$terms, function(xx) 
  data.frame(var=xx$var,model=xx$model, id = c(xx$id, NA)[1])
  ))
varInfo$name = paste(varInfo$var, varInfo$model, sep='_')


gammaHat = parMle[grep("gamma", names(parMle))]

```

```{r somestuff}

newdata = data.frame(sqrtPm = seq(0, sqrt(200), len=200), ecoRegionInt = 'Global')

parMle = fit$obj$env$last.par.best[
  grep("gamma", names(fit$obj$env$last.par.best), invert=TRUE)
  ]

betaHat = parMle[names(parMle) == 'beta']
#betaHat = betaHat[fit$beta_info$Xid]
names(betaHat) = fit$beta_info$var

whichIsGamma = which(names(fit$obj$env$last.par.best) == "gamma")
gammaHat = fit$obj$env$last.par.best[whichIsGamma]

varInfo = do.call(rbind, lapply(fit$terms, function(xx) 
  data.frame(var=xx$var,model=xx$model, id = c(xx$id, NA)[1])
  ))


plot(factor(fit$gamma_info$var), gammaHat)




precGammaHat = fit$obj$env$spHess(fit$obj$env$last.par)
precGammaHat = forceSymmetric(precGammaHat[whichIsGamma, whichIsGamma])
varGammaHat = solve(precGammaHat)
Nsim = 10
gammaSim = t(mvtnorm::rmvnorm(Nsim, gammaHat, as.matrix(varGammaHat)))


gammaHat[grep("date", fit$gamma_info$var, invert=TRUE)]

# identify the random effects needed in newdata
Sterms = which(varInfo[,'var'] %in% names(newdata))

newDesignMat = hpoltest:::getNewXA(fit$terms[Sterms], newdata)

betaHatHere = betaHat[grep(paste(unique(varInfo[Sterms,'var']), collapse='|'), names(betaHat))]
newdata$fixed = drop(newDesignMat$X %*% betaHatHere)


Sid = unlist(lapply(fit$terms[Sterms], function(xx) xx$id))
gammaIndices = which(fit$gamma_info$id %in% Sid)
gammaHatHere = gammaHat[gammaIndices]
varGammaHatHere = varGammaHat[gammaIndices, gammaIndices]

gammaSimHere = gammaSim[gammaIndices,]
simHere = newDesignMat$A %*% gammaSim + newdata$fixed

newdata$mean = drop(newDesignMat$A %*% gammaHatHere) + newdata$fixed
newdata$sd =sqrt(apply( (newDesignMat$A %*% varGammaHatHere) * newDesignMat$A, 1, sum))


ciMat = array(c(1, -1.95996398454005, 1, 1.95996398454005), dim = c(2,2), 
              dimnames = list(c("mean", "sd"), paste0(c("0.025", "0.975"), 'quant')))

lowerUpper = as.matrix(newdata[,c('mean','sd')]) %*% ciMat
newdata = cbind(newdata, as.data.frame(lowerUpper))



matplot(
  newdata[,1]^2,
  newdata[,c('mean','0.025quant','0.975quant')],
  ylim = range(newdata[-(1:20),c('0.025quant','0.975quant')]),
  type='l', lty=c(1,2,2), col='black', xaxs='i', bty='n',
  xlab='exposure', ylab='log rr'
)

# joint confidence regions
toKeep = round(seq(1, nrow(newdata), len = 7+2)[seq(from=2, by=1, len=7)])
toKeep = toKeep[-3]
varFull =  Matrix::forceSymmetric(
  tcrossprod(newDesignMat$A[toKeep,] %*% varGammaHatHere, 
             newDesignMat$A[toKeep,]))
#cholVar = solve(chol(varFull))
#stuff = excursions::simconf(0.8, newdata$mean, Q.chol = cholVar)
#matplot(newdata$tempClean, as.data.frame(stuff[c('a','b')]))

```



