```{r setup, include=FALSE}
library('knitr')

knitr::knit_hooks$set(margins = Pmisc::hook_plot_margins)

knitr::opts_chunk$set(echo=FALSE, prompt=TRUE, comment=NA,
    dev='pdf', margins=1, fig.cap=' ',
  fig.path=file.path('figure','moreBayes'),    
    fig.width=5, fig.height=5, half=NULL,
    tidy=TRUE,tidy.opts=list(indent=2, width.cutoff=45)
)

knitr::opts_hooks$set(half = function(options) {
    options$tidy.opts = list(width.cutoff = 12)#list(options$tidy.opts$width.cutoff/2)
    options
  })
options(width=80)
```




```{r ecoRegionmap}
SstoreDir = c('/store/patrick/copernicus/agg', '~/Downloads/agg')
storeDir = SstoreDir[1]
if(!dir.exists(storeDir)) storeDir = SstoreDir[2]

indiaEcoRegions = terra::unwrap(readRDS(file.path(storeDir, "indiaEcoRegions.rds")))
mapmisc::map.new(indiaEcoRegions)
terra::plot(indiaEcoRegions, add=TRUE)
terra::plot(indiaEcoRegions[4,], add=TRUE, col='yellow')
```

g


```{r setup2, eval=FALSE}


library('data.table')
# /home/patrick/Admin/globalHealth/indiaSpatial/daily.Rmd


deaths = as.data.table(readRDS( file.path(storeDir, "indiaCC.rds")))



# trransform variables
deaths$sqrtPm = sqrt(pmin(deaths$pm,1000))
deaths$timeIid = as.numeric(deaths$date)

# table(deaths$ecoRegion, deaths$temp < -10)

deaths$tempClean = pmax(deaths$temp, -5)


deaths$dom = as.numeric(format(deaths$date, '%d'))
deaths[deaths$dom == Hmisc::monthDays(deaths$date), 'dom'] = 31
deaths[format(deaths$date, '%m%d') == '0101', 'dom'] = 0
deaths$dom = relevel(factor(deaths$dom), '1')
deaths$month = format(deaths$date, '%m')


dataMedSimple =
  deaths[
    format(deaths$date, '%b%d') != 'Jan01'
    & deaths$tempClean >= (0) # & deaths$ecoRegion %in% 1:10 #setdiff(1:20, c(1,7,19)) # regions 1, 7, 19 have some very low temperatures.
    , ]
save(dataMedSimple, file='dataMedSimple.RData')
```




```{r fit, eval=FALSE}
library('hpolcc')
load("dataMedSimple.RData")

# add day iid
res <- hpolcc::hnlm(
  formula= medical ~ #f(date, model='iid') +
#    humidity + 
#    f(sqrtPm, model='hiwp', ref_value = 8, p=2, 
#      knots = seq(0,32, by=2),
#      group_var = ecoRegion) + 
    f(tempClean, model='hiwp',ref_value = 20, p=3, 
      knots = seq(0, 45, by=2.5), 
    group_var = ecoRegion), 
  data=dataMedSimple, 
  config = list(transform_theta = TRUE, 
  dirichlet= TRUE, 
                boundary_is_random = TRUE,
                num_threads=parallel::detectCores(),
                Nclusters = 50*parallel::detectCores(),
  verbose=TRUE),
  control_inner=list(report.level=0),
  cc_design =  c("cell","ecoRegion", "yearWeek3Dow")
  )
saveRDS(resTempPm, file='resTempPm.rds')
resTempPmFixed <- hpolcc::hnlm(
  formula= medical ~ #f(date, model='iid') +
    humidity + 
    f(sqrtPm, model='hiwp', ref_value = 8, p=2, 
      knots = seq(0,32, by=2),
      group_var = ecoRegion) + 
    f(tempClean, model='hiwp',ref_value = 20, p=3, 
      knots = seq(0, 45, by=2.5), 
    group_var = ecoRegion), 
  data=dataMedSimple, 
  config = list(transform_theta = TRUE, 
  dirichlet= TRUE, 
                boundary_is_random = FALSE,
                num_threads=parallel::detectCores(),
                Nclusters = 50*parallel::detectCores()),
  control_inner=list(report.level=0),
  cc_design =  c("cell","ecoRegion", "yearWeek3Dow"),
  for_dev=TRUE, verbose=TRUE
  )

saveRDS(resTempPmFixed, file='resTempPmFixed.rds')
# res = readRDS('res.rds')
```


```{r sparsePlot, eval=FALSE}
par(mar=c(3,3,0,0), bty='n')
bob= terra::rast(as.matrix(1.1*resTempPm$groups$firstDeriv[, 
  1 + resTempPm$groups$groups$i]))
terra::plot(bob, asp=FALSE, col=c('white','black'))
abline(v = resTempPm$groups$groups$p,
       col = 'blue',
       lty = 1, lwd=.2)
```

```{r fitModel, eval=FALSE}
theFile = 'resTempPm.rds'
#theFile = 'resTempPmFixed.rds'
res = readRDS(theFile)
library('hpolcc')
adFunFull = getAdFun(res$parameters_and_gamma, res$tmb_data, modifyList(res$config, list(verbose=TRUE)))

assign("file", gsub("rds$", "txt", theFile), res$cache)
if(file.exists(get("file", res$cache))) file.remove(get("file", res$cache))

for_rep = c(length(res$config$beta), length(res$config$theta)-1, 1)
start_par = rep(c(0,-4, -1), for_rep)

mleT = trustOptim::trust.optim(
    start_par,
    fn =outer_fn,
    gr = outer_gr,
    method = 'SR1', 
    control = list(start.trust.radius = 0.05, REPORT=1, trace=10),
    data=res$tmb_data, config = res$config, cache =  res$cache, 
    control_inner = res$control_inner,
    adFunFull = adFunFull
  )
mleT$extra = loglik(
  mleT$solution,
  gamma_start = get("gamma_start", res$cache),
 data=res$tmb_data, config = res$config, control = res$control_inner,
 deriv = 0)
saveRDS(mleT, file=gsub("^res", "mleT", theFile))

mleX = optim(
    mleT$solution,
    fn = outer_fn,
    gr = outer_gr,
    method = 'L-BFGS-B', 
    lower = rep(c(-0.5, log(1e-5),log(1e-3)), for_rep),
    upper = rep(c(0.5, 0, 0), for_rep),
    control = list(trace=3, REPORT=1, 
      parscale = rep(c(1e-3, 10, 1), for_rep)
      ),#start.trust.radius = 0.05, REPORT=1, trace=10),
    data=res$tmb_data, config = res$config, cache =  res$cache, 
    control_inner = res$control_inner,
    adFunFull = adFunFull
  )

mleX$extra = loglik(
  mleX$par,
  gamma_start = get("gamma_start", res$cache),
 data=res$tmb_data, config = res$config, control = res$control_inner,
 deriv = 0)
saveRDS(mleX, file=gsub("^res", "mleX", theFile))
```

```{r checkDeriv}
mleX$par
configInner = res$config
Nbeta = nrow(res$tmb_data$XTp)
configInner$beta = mleX$par[seq(1, len=Nbeta)]
configInner$theta = mleX$par[seq(Nbeta+1, length(mleX$par))]

adFunInner = getAdFun(mleX$extra$solution, data=res$tmb_data, config=configInner)
bob = grad(mleX$extra$solution, data=res$tmb_data, config=res$config, adFun = adFunInner)
gradFn2 = function(x, xSeq) {
  newx = mleX$extra$solution
  newx[xSeq] = x
  grad(newx, data=res$tmb_data, config=res$config, adFun=adFunInner)
}
xSeq = 1:4
numDeriv::hessian(gradFn2, mle$extra$solution[xSeq], xSeq = xSeq)
mleX$extra$hessian[xSeq, xSeq]



Dpar = 4;N=5
parMat = data.frame(mleX$par)[,rep(1, N)]
Sx = seq(-0.01,0.01, len=ncol(parMat)) + mleX$par[Dpar]
Sx1 = Sx[-1] - diff(Sx)/2
parMat[Dpar,] = Sx

control1 = list(
  maxit = 5000L,
  gtol  = 1e-13,   # gradient-norm tolerance
  xtol  = 1e-13,   # parameter step tolerance
  ftol  = 1e-12,   # objective change tolerance
  stop.trust.radius = 1e-15,
  cg.tol = 1e-15,
  prec   = 1e-15,
  report.level = 8L, report.freq = 1L
  )

baseLik = loglik(
  mleX$par,
  gamma_start = get("gamma_start", res$cache),
 data=res$tmb_data, config = res$config, control = control1, 
 deriv=1, check=FALSE)
assign("gamma_start", baseLik$solution, envir=res$cache)

rx = mapply(
  loglik,
  parameters = as.list(parMat),
  MoreArgs = list(
    gamma_start = get('gamma_start', res$cache),
  control = control1,
  deriv=0, data=res$tmb_data, config = res$config, adFunFull = adFunFull),
  SIMPLIFY=FALSE
  )



Slik = unlist(lapply(rx, "[[", "minusLogLik"))
plot(Sx, Slik)
plot(Sx1, diff(Slik)/mean(diff(Sx)),  pch=16, xlim = range(Sx), type='o')
abline(h=baseLik$deriv[Dpar, 'dL'])
abline(v=baseLik$parameters[Dpar])


Sdet = unlist(lapply(rx, "[[", "halfLogDet"))
plot(Sx, Sdet)
Sy = diff(Sdet)/mean(diff(Sx))
plot(Sx1, Sy,  pch=16, xlim = range(Sx),type='o', 
     ylim = range(c(Sy, baseLik$deriv[Dpar, 'dDet'])))
abline(h=baseLik$deriv[Dpar, 'dDet'])
abline(v=baseLik$parameters[Dpar])

Sdens = unlist(lapply(rx, '[[', 'fval'))
Ddens = diff(Sdens)/diff(Sx)
plot(Sx1, Ddens,type='o')
abline(v=baseLik$parameters[Dpar])
abline(h=baseLik$deriv[Dpar,'gradTheta'])

```




```{r theResults}
library('hpolcc')
theFile = 'resTempPm.rds'
#theFile = 'resCvd.rds'

theData = readRDS(theFile)
result = readRDS(gsub("^res", "mleT", theFile))

result$parameters = formatParameters(
  x=result$extra$fullParameters, 
  obj=theData, TRUE)
result$parameters$theta
result$parameters$beta

HtildeChol = result$extra$cholHessian
#HtildeChol = Matrix::Cholesky(result$extra$hessian, LDL=TRUE, perm=TRUE)
HtildeCholEx = Matrix::expand2(HtildeChol)


Hrecon = HtildeCholEx$P1. %*% (HtildeCholEx$L1 %*% HtildeCholEx$D %*% HtildeCholEx$L1.) %*% HtildeCholEx$P1

#quantile(Matrix::diag(Hrecon) - Matrix::diag(result$extra$hessian))
#plot(Matrix::diag(Hrecon) , Matrix::diag(result$extra$hessian), log='xy')
#abline(0,1)


HtildeCholHard= Matrix::chol(result$extra$hessian)
HtildeCholInv = Matrix::solve(HtildeCholHard)

Nsim = 500
predSeq = list(
  tempClean = seq(0,45,by=0.2),
  sqrtPm = sqrt(seq(0,1000, by=2))
)
newConstr = list(tempClean = 25, sqrtPm = sqrt(25))

predSeq = predSeq[names(predSeq) %in% unlist(lapply(theData$terms, '[[', 'var'))]

simInd = matrix(
  rnorm(Nsim * nrow(result$extra$hessian)),
  nrow(result$extra$hessian), Nsim)

# H = Pt L D Lt P 
# V = Pt Ltinv Dinv Linv P

#simInd1 = simInd/sqrt(HtildeCholEx$D@x)
#simGamma = HtildeCholEx$P1. %*% Matrix::solve(HtildeCholEx$L1., simInd1) +
#  result$extra$solution
simGamma = HtildeCholInv %*% simInd
rownames(simGamma) = rownames(result$parameters$gamma)


Sref = unlist(lapply(theData$terms, '[[', "ref_value"))
Svar = unlist(lapply(theData$terms, '[[', "var"))

simGlobal = newConstrIndex = simF = fixedPart = predX = list()

    
simGlobal = simF = fixedPart = predX = newXA = list()
colsBetaClean = gsub("_fpoly_", "", names(result$parameters$beta))

for(D in names(predSeq)) {
  newDf = data.frame(x = predSeq[[D]], ecoRegion = NA)
  colnames(newDf)[1] = D
  newXA[[D]] = hpolcc:::getNewXA(
    terms = theData$terms, 
    df= newDf
  )
  theCols = intersect(colnames(newXA[[D]]$X), colsBetaClean)
  fixedPart[[D]] = newXA[[D]]$X[,theCols,drop=FALSE] %*% 
    result$parameters$beta[match(theCols, colsBetaClean)]

  colsA = grep(paste0(D, "_hiwp_GLOBAL_"), colnames(newXA[[D]]$A), value=TRUE, ignore.case=TRUE)
  simF[[D]] = newXA[[D]]$A[,colsA] %*% simGamma[colsA,]

  simGlobalHere= simF[[D]] + fixedPart[[D]]
  newConstrIndex[[D]] = which.min(abs(predSeq[[D]] - newConstr[[D]]))
  toSubtract = matrix(simGlobalHere[newConstrIndex[[D]],],
    nrow(simGlobalHere), ncol(simGlobalHere), byrow=TRUE)
  simGlobal[[D]] = simGlobalHere - toSubtract
}
Sregions = levels(result$parameters$gamma$group)
```

```{r params}
result$parameters$beta
result$parameters$theta
```

```{r globalRes, fig.cap='Common component', fig.subcap = c("temperature", "PM 2.5")}
par(mar=c(3,3,0,0), bty='l')
if("tempClean" %in% names(simGlobal)) {
theY = 100*(exp(simGlobal[["tempClean"]])-1)
matplot(predSeq[["tempClean"]], theY, type='l',
  col='#00000010', lty=1, xaxs='i',
  xlab='degrees C', ylab = '100 x (RR-1)',
  ylim = c(-1/3, 31), xlim = c(6, 38))
theYq = t(apply(theY, 1, quantile, probs=c(0.025, 0.975, 0.5)))
matlines(predSeq[["tempClean"]], theYq, lty=c(2,2,1), lwd=c(1,1,2), col='blue')
}

if("sqrtPm" %in% names(simGlobal)) {

theY =  100*(exp(simGlobal[["sqrtPm"]])-1)
theX = predSeq[["sqrtPm"]]^2
matplot(theX, theY , type='l',
  col='#00000010', lty=1, xaxs='i',
  xlim = c(0,600), ylim = c(-4, 12),
  xlab = 'PM 2.5', ylab = '100 (RR-1)')
theYq = t(apply(theY, 1, quantile, probs=c(0.025, 0.975, 0.5)))
matlines(theX, theYq, lty=c(2,2,1), lwd=c(1,1,2), col='blue')
}
```


```{r byRegionTemp, fig.cap='temperature', fig.subcap = Sregions, fig.height=3, fig.width=5}
Dvar = "tempClean"
simTemp = list()
for(D in Sregions) {
  gammaNames = grep(paste0(Dvar,"_h(iwp|rpoly)_",D,"_"), colnames(newXA[[Dvar]]$A), value=TRUE)
  Anames1 = grep("hiwp", gammaNames, value=TRUE)
  Anames = gsub(paste0("_", D, "_"), "_global_",Anames1)
  
  Xnames1 = grep("hrpoly", gammaNames, value=TRUE)
  Xnames = gsub(paste0("_hrpoly_", D, "_"), "", Xnames1)
  
  simF2 = "%*%"(newXA[[Dvar]]$A[,Anames], simGamma[Anames1,]) 
  simX2 = "%*%"(newXA[[Dvar]]$X[,Xnames,drop=FALSE], simGamma[Xnames1,])   
  
  simSum2 = simGlobal[[Dvar]] + simF2 + simX2
  toSubtract = matrix(simSum2[newConstrIndex[[Dvar]],],
    nrow(simF2), ncol(simF2), byrow=TRUE)
  simTemp[[D]] = 100*(exp(simSum2 - toSubtract)-1)

  theY = simTemp[[D]]
  matplot(predSeq[[Dvar]], theY, type='l',
    xlab = 'degrees C', ylab='100 x (RR-1)',
    col='#00000010', lty=1, xaxs='i',
    ylim = c(-5, 50), xlim = c(6, 38))
  theYq = t(apply(theY, 1, quantile, probs=c(0.025, 0.975, 0.5)))
  matlines(predSeq[[Dvar]], theYq, lty=c(2,2,1), lwd=c(1,1,2), col='blue')

}
```


```{r byRegionPm, fig.cap='PM2.5', fig.subcap = Sregions, fig.height=3, fig.width=5}
Dvar = "sqrtPm"
simPm = list()
for(D in Sregions) {
  gammaNames = grep(paste0(Dvar,"_h(iwp|rpoly)_",D,"_"), colnames(newXA[[Dvar]]$A), value=TRUE)
  Anames1 = grep("hiwp", gammaNames, value=TRUE)
  Anames = gsub(paste0("_", D, "_"), "_global_",Anames1)
  
  Xnames1 = grep("hrpoly", gammaNames, value=TRUE)
  Xnames = gsub(paste0("_hrpoly_", D, "_"), "", Xnames1)
  
  simF2 = "%*%"(newXA[[Dvar]]$A[,Anames], simGamma[Anames1,]) 
  simX2 = "%*%"(newXA[[Dvar]]$X[,Xnames,drop=FALSE], simGamma[Xnames1,])   
  
  simSum2 = simGlobal[[Dvar]] + simF2 + simX2
  toSubtract = matrix(simSum2[newConstrIndex[[Dvar]],],
    nrow(simF2), ncol(simF2), byrow=TRUE)
  simPm[[D]] = 100*(exp(simSum2 - toSubtract)-1)

  theX = predSeq[[Dvar]]^2
  theY = simPm[[D]]
  par(mar=c(2,2,0,0), bty='n')
  matplot(theX, theY, type='l',
  xlab = 'pm25', ylab='100 x (RR-1)',
    col='#00000010', lty=1, xaxs='i',
    ylim = c(-4, 15), xlim = c(0, 600))
    theYq = t(apply(theY, 1, quantile, probs=c(0.025, 0.975, 0.5)))
  matlines(theX, theYq, lty=c(2,2,1), lwd=c(1,1,2), col='blue')

}
```


```{r avgRes, fig.cap='Average', fig.subcap = c("temperature", "PM 2.5")}

par(mar=c(3,3,0,0), bty='l')
  toAvg = do.call(abind::abind, c(lapply(simTemp, as.matrix), list(along=3)))
  avgHere = apply(toAvg, 1:2, mean)
  matplot(predSeq[["tempClean"]], avgHere, type='l',
    xlab = 'deg C', ylab='100 x (RR-1)',
  col='#00000010', lty=1, xaxs='i',
  ylim = c(-1/3, 31), xlim = c(6, 38))
theYq = t(apply(avgHere, 1, quantile, probs=c(0.025, 0.975, 0.5)))
matlines(predSeq[["tempClean"]], theYq, lty=c(2,2,1), lwd=c(1,1,2), col='blue')


  toAvg = do.call(abind::abind, c(lapply(simPm, as.matrix), list(along=3)))
  avgHere = apply(toAvg, 1:2, mean)
  theX = predSeq[["sqrtPm"]]^2
  matplot(theX, avgHere , type='l',
  col='#00000010', lty=1, xaxs='i',
  xlim = c(0,600), ylim = c(-4, 12),
  xlab = 'PM 2.5', ylab = '100 (RR-1)')
theYq = t(apply(avgHere, 1, quantile, probs=c(0.025, 0.975, 0.5)))
matlines(theX, theYq, lty=c(2,2,1), lwd=c(1,1,2), col='blue')
```

