---
title: "India"
geometry: margin=1in
output: pdf_document
header-includes:
  - |
    ```{=latex}
    \usepackage[table]{xcolor}
    \expandafter\def\csname ver@subfig.sty\endcsname{}
    \usepackage{graphicx,subcaption}
    \makeatletter\@ifundefined{subfloat}{\newcommand{\subfloat}[2][need a sub-caption]{\subcaptionbox{#1}{#2} }}{\renewcommand{\subfloat}[2][need a sub-caption]{\subcaptionbox{#1}{#2} }}\makeatother
    ```
---


```{r setup, include=FALSE}
knitr::knit_hooks$set(margins = Pmisc::hook_plot_margins)
knitr::knit_hooks$set(plot = knitr::hook_plot_tex)

knitr::opts_chunk$set(
  echo = FALSE, prompt = TRUE, comment = NA,
  dev = "pdf", margins = 1, fig.cap = " ", fig.pos = "hp",
  fig.path = file.path("figure", "moreBayes"),
  fig.width = 5, fig.height = 5, half = NULL,
  tidy = TRUE, tidy.opts = list(indent = 2, width.cutoff = 45)
)

options(width = 80)
```


```{r ecoRegionData}
s_store_dir <- c("/store/patrick/copernicus/agg", "~/Downloads/agg")
store_dir <- s_store_dir[1]
if (!dir.exists(store_dir)) store_dir <- s_store_dir[2]

india_eco_regions <- terra::unwrap(readRDS(file.path(store_dir, "indiaEcoRegions.rds")))
india_eco_regions$name <- gsub(
  " AND ", ", ",
  gsub(" E.O.REGION|[(].*[)]|TO PERHUMID.*|PENINSULA ", "", india_eco_regions$physio_reg)
)
india_eco_regions$id_name <- paste(india_eco_regions$objectid, india_eco_regions$name)

india_eco_regions$col <- rep_len(
  c(
    RColorBrewer::brewer.pal(12, "Set3"),
    RColorBrewer::brewer.pal(8, "Set2")
  ),
  length(india_eco_regions)
)


# objectid is deaths$eco_region
```

```{r worldPopByRegion, cache=TRUE}
year <- 2020
dir.create("data/gpw", recursive = TRUE, showWarnings = FALSE)

# geodata::population returns GPW population density (people per km^2)
pop_density <- geodata::population(year, res = 5, path = "data/gpw")

eco <- terra::project(india_eco_regions, terra::crs(pop_density))

pop_density_india_eco <- terra::crop(pop_density, eco)
pop_density_india_eco <- terra::mask(pop_density_india_eco, eco)

# Convert density to estimated population count per cell before extraction.
cell_area_km2 <- terra::cellSize(pop_density_india_eco, unit = "km")
pop_count <- pop_density_india_eco * cell_area_km2

eco_pop <- terra::extract(
  pop_count,
  eco,
  fun = sum,
  na.rm = TRUE,
  exact = TRUE
)

eco$gpw_2020 <- eco_pop[, 2]

eco_pop_df <- data.frame(
  objectid = eco$objectid,
  physio_reg = eco$physio_reg,
  gpw_2020 = eco$gpw_2020
)

eco_pop_df$weight <- eco_pop_df$gpw_2020 / sum(eco_pop_df$gpw_2020)
```



```{r deaths_data, eval=FALSE}
library("data.table")
# /home/patrick/Admin/globalHealth/indiaSpatial/daily.Rmd

deaths <- as.data.table(readRDS(file.path(store_dir, "indiaCC.rds")))
data.table::setnames(
  deaths,
  old = c("ecoRegion", "yearWeek3Dow"),
  new = c("eco_region", "year_week3_dow"),
  skip_absent = TRUE
)

# trransform variables
deaths$sqrt_pm <- sqrt(pmin(deaths$pm, 1000))
deaths$time_iid <- as.numeric(deaths$date)

deaths$temp_div10 <- pmax(deaths$temp, -5)/10


deaths$dom <- as.numeric(format(deaths$date, "%d"))
deaths[deaths$dom == Hmisc::monthDays(deaths$date), "dom"] <- 31
deaths[format(deaths$date, "%m%d") == "0101", "dom"] <- 0
deaths$dom <- droplevels(relevel(factor(deaths$dom), "1"))
deaths$month <- format(deaths$date, "%m")

save(deaths, file = "deaths.RData")
```




```{r fit, cache=TRUE}
# devtools::install_github("eborgine/adlaplace")
# devtools::install_github("eborgine/hpolcc")

library("hpolcc")

load("~/research/adlaplace/applications/india/deaths.RData")


res_pm_temp <- hnlm(
  formula = medical ~ dom +
    f(sqrt_pm,
      model = "hiwp", ref_value = 8, p = 2,
      knots = seq(0, 32, by = 2),
      by = "eco_region",
      init = 1e-1,
      lower = 1e-12
    ) +
    f(temp_div10,
      model = "hiwp", ref_value = 25 / 10, p = 3,
      knots = seq(-5, 42.5, by = 2.5) / 10,
      by = "eco_region",
      init = 1e-1,
      lower = 1e-12
    ) +
    f(model = "overdispersion", init = 0.1, parscale = 10),
  data = deaths, # [seq(1, 5e5),],
  cc_design = c("cell", "eco_region", "year_week3_dow"),
  config = list(
    transform_theta = TRUE,
    num_threads = parallel::detectCores(),
    num_groups = 1e4,
    verbose = TRUE
  ),
  control = list(
    maxit = 1000,
    trace = 3,
    REPORT = 1
  ),
  control_inner = list(report.level = 0, trust.iter = 5000),
  for_dev = FALSE
)

saveRDS(res_pm_temp, file = "resPmTemp.rds")
#invisible(sapply(list.files("~/research/adlaplace/hpolcc/R", pattern = "\\.R$", full.names = TRUE), source))
```


```{r par_table}
res <- res_pm_temp #readRDS("resPmTempR.rds")
s_var <- names(res$sample$sim)
s_var_names <- c(temp_div10 = "temperature", sqrt_pm = "PM2.5")[s_var]

theta_table = res$parameters$theta[,c("term","model","mle", "init","lower", "parscale", "log_mle")]
theta_table$term = s_var_names[theta_table$term]
theta_table
```

```{r globalSetup}
the_x_lim <- list(
  temp_div10 = c(4, 38),
  sqrt_pm = c(0, 450)
)

for_global <- expand.grid(
  var = s_var,
  type = c("Common", "Pop Avg"), stringsAsFactors = FALSE
)
for_global$var_name <- s_var_names[for_global$var]
for_global$subcap <- paste(for_global$var_name, for_global$type)

the_y_lim <- list()

for (d in s_var) {
  x_here <- res$sample$x[[d]]
  if (grepl("sqrt", d)) x_here <- x_here^2
  if (grepl("div10", d)) x_here <- 10*x_here

  use_x_here <- x_here <= max(the_x_lim[[d]]) &
    x_here >= min(the_x_lim[[d]])

  range1 <- range(
    res$sample$quantile$common[[d]][use_x_here, , drop = FALSE]
  )
  if (!is.null(res$sample$envelope$common[[d]])) {
    range2 <- range(
      res$sample$envelope$common[[d]][use_x_here, , drop = FALSE]
    )
  } else {
    range2 <- NULL
  }
  the_y_lim[[d]] <- range(c(-2, 100 * (c(range1, range2) - 1)))
}
```

```{r globalRes, fig.cap='Common component', fig.subcap = for_global$subcap, out.width='0.48\\linewidth', fig.height=5, fig.width=5}
par(mar = c(3, 3, 0, 0), bty = "l")

for (d in seq_len(nrow(for_global))) {
  d_var <- for_global[d, "var"]
  x_here <- res$sample$x[[d_var]]
  if (grepl("sqrt", d_var)) x_here <- x_here^2
  if (grepl("div10", d_var)) x_here <- x_here*10

  plot(NA,
    xlim = the_x_lim[[d_var]], ylim = the_y_lim[[d_var]],
    xlab = s_var_names[d_var], ylab = "100 x (RR-1)",
    xaxs = "i", yaxs = "i"
  )

  if (for_global[d, "type"] == "Common") {
    sample <- 100 * (res$sample$sim[[d_var]] - 1)
    matlines(x_here, sample, type = "l", col = "#00000010", lty = 1)
    envelope_here <- res$sample$envelope$common[[d_var]]
    quantiles_here <- res$sample$quantiles$common[[d_var]]
  } else {
    envelope_here <- res$sample$envelope$weighted[[d_var]]
    quantiles_here <- res$sample$quantiles$weighted[[d_var]]
  }
  if (!is.null(quantiles_here)) {
    matlines(x_here, 100 * (quantiles_here - 1),
      lty = c(2, 1, 2), lwd = c(1, 3, 1), col = "green"
    )
  }
  if (!is.null(envelope_here)) {
    matlines(x_here, 100 * (envelope_here - 1),
      lty = c(3, 2, 3), lwd = c(1, 2, 1), col = "red"
    )
  }
}
```




```{r byRegionTemplate}
#, eval=FALSE, include=FALSE}
x_here <- res$sample$x[[d_var]]
s_group = names(res_pm_temp$sample$envelope$group[[d_var]])

if (grepl("sqrt", d_var)) x_here <- x_here^2
  if (grepl("div10", d_var)) x_here <- x_here*10

sim_global_here_y <- 100 * (res$sample$quantiles$common[[d_var]] - 1)


for (d_group in s_group) {
  group_key <- as.character(d_group)
  the_ye <- 100 * (res$sample$envelope$group[[d_var]][[group_key]] - 1)
  the_yq <- 100 * (res$sample$quantiles$group[[d_var]][[group_key]] - 1)

  if (is.null(the_yq)) {
    warning("missing group quantiles for ", d_var, " / ", d_group)
    next
  }

  plot(x_here, sim_global_here_y[, 2],
    type = "l",
    xlab = d_var, ylab = "100 x (RR-1)",
    col = "grey", xaxs = "i", lwd = 4,
    ylim = the_y_lim[[d_var]], xlim = the_x_lim[[d_var]]
  )
  matlines(x_here, the_yq,
    lty = c(2, 1, 2), lwd = c(1, 2, 1), col = "green"
  )
  matlines(x_here, the_ye,
    lty = c(2, 1, 2), lwd = c(1, 2, 1), col = "red"
  )
}
```


```{r byRegionSetup1}
d_var <- grep("temp", names(res$sample$sim), value = TRUE)
s_group <- names(res$sample$quantile$group[[d_var]])
```

```{r byRegion1, fig.cap=s_var_names[d_var], fig.subcap = s_group, fig.height=4, fig.width=4, ref.label = 'byRegionTemplate', eval=(length(d_var)>0), out.width='0.23\\linewidth', fig.align='center'}
```

```{r byRegionSetup2}
d_var <- grep("[pP]m$", names(res$sample$sim), value = TRUE)
s_group <- names(res$sample$quantile$group[[d_var]])
```

```{r byRegion2, fig.cap=s_var_names[d_var], fig.subcap = s_group, fig.height=4, fig.width=4, ref.label = 'byRegionTemplate', eval=(length(d_var)>0), out.width='0.23\\linewidth', fig.align='center'}
```




```{r ecoRegionmap, fig.cap = 'Eco regions', fig.subcap = c('reginos','legend') ,fig.height=5, fig.width=5, out.width = '0.48\\linewidth'}
mapmisc::map.new(india_eco_regions)
terra::plot(india_eco_regions, add = TRUE, col = india_eco_regions$col)
terra::text(terra::centroids(india_eco_regions), india_eco_regions$objectid)

mapmisc::map.new(india_eco_regions)
mapmisc::legendBreaks(
  "left",
  col = rev(india_eco_regions$col),
  legend = rev(india_eco_regions$id_name),
  cex = 0.7, bty = "n", width = Inf
)
```


```{r ecoTable, results='asis', include=FALSE}
knitr::kable(
  mapmisc::legendTable(data.frame(
    label = india_eco_regions$id_name,
    col = india_eco_regions$col
  ), type = "latex"),
  format = "latex", escape = FALSE,
  align = c("c", "l"),
  col.names = c("", "Eco region"),
  caption = "Eco-regions used in the analysis"
) |>
  kableExtra::kable_styling(
    latex_options = c("hold_position", "striped"),
    full_width = FALSE,
    font_size = 9
  ) |>
  kableExtra::column_spec(1, latex_column_spec = "p{0.05\\\\linewidth}") |>
  kableExtra::column_spec(2, latex_column_spec = "p{0.7\\\\linewidth}")
```

```{r derivJointDens}

res$config$gamma = rep(0.1, length(res$config$gamma))
res$config$theta = rep(-1, length(res$config$theta))

#res2 = res
#groupHere = res$config$groups[,13, drop=FALSE]
#res2$config$groups = Matrix::sparseMatrix(
#  j = rep(0,1), i=groupHere@i[1], x=1, dims = dim(groupHere), index1=FALSE
#)

  ad_fun <- adlaplace::getAdFun(
    res$tmb_data,
    res$config
  )

x_joint = c(
  res$parameters_info$beta$init,
  rep(1, nrow(res$parameters_info$gamma)),
  res$parameters_info$theta$init
  )
x_joint = c(res$config$beta, res$config$gamma, res$config$theta)  
# Perturb one parameter and compare analytic gradient to finite differences.
Dpar <- length(res$config$beta)+length(res$config$gamma) -1#length(x_joint)-3L
Npar <- 13
parDf <- data.frame(x = x_joint)[rep(1, Npar)]
Sx <- seq(-0.1, 0.1, length.out = Npar) + x_joint[Dpar]
SxD <- Sx[-1] - diff(Sx) / 2
parDf[Dpar, ] <- Sx

Sgroups <- seq.int(from = 0L, length.out = length(ad_fun$sparsity))
#Sgroups =  0L

#bob1 = adlaplace::grad(x_joint, ad_fun, Sgroups = Sgroups)
#bob2 = adlaplace::hess(x_joint, ad_fun, Sgroups = Sgroups, verbose=TRUE)

dens1 <- mapply(
  adlaplace::jointLogDens,
  x = as.list(parDf),
  MoreArgs = list(backendContext = ad_fun, Sgroups = Sgroups),
  SIMPLIFY = TRUE
)

par(mfrow=c(2,1))
plot(Sx, dens1, xlab = sprintf("x[%d]", Dpar), ylab = "jointLogDens")


grad1 <- mapply(
  adlaplace::grad,
  x = as.list(parDf),
  MoreArgs = list(backendContext = ad_fun, inner = FALSE, Sgroups = Sgroups),
  SIMPLIFY = TRUE
)

fdGrad <- diff(dens1) / diff(Sx)
gradAlongPath <- grad1[Dpar, ]
gradMid <- 0.5 * (gradAlongPath[-1] + gradAlongPath[-length(gradAlongPath)])

plot(Sx, gradAlongPath, xlab = sprintf("x[%d]", Dpar), ylab = "d jointLogDens / dx")
lines(SxD, fdGrad, lwd = 2, col = 2)
legend("topleft", legend = c("analytic", "finite diff"), lty = 1, col = c(1, 2), bty = "n")

max_abs_err <- max(abs(gradMid - fdGrad))
max_abs_err

hess1 <- mapply(
  adlaplace::hess,
  x = as.list(parDf),
  MoreArgs = list(backendContext = ad_fun, inner = FALSE),
  SIMPLIFY = FALSE
)
hess1a = lapply(hess1, as.matrix)
hess1b = do.call(abind::abind, c(hess1a, list(along=3)))[Dpar,,]

par(mfrow=c(4,4), mar=c(3,3,0,0))

parSeq = seq(Dpar-8, len=16)
if(any(parSeq < 1)) parSeq = parSeq + min(parSeq)+1
if(any(parSeq > length(x_joint))) parSeq = parSeq - (max(parSeq) + length(x_joint))
for(D in 1:prod(par("mfrow"))) {
  plot(Sx, hess1b[D,])
  fdGrad <- diff(grad1[D,]) / diff(Sx)
  lines(SxD, fdGrad)
}

```



```{r testLogLgrad, eval=FALSE, include=FALSE}
res = res_pm_temp
x_params =  res$objects$cache$last_par_gr
res$config$gamma = res$objects$cache$gamma

ll1 = adlaplace::logLikLaplace(x_params, 
  config = res$config, 
  gamma=res$config$gamma, 
  adFun = ad_fun, deriv=TRUE, 
  control = list(report.level = 4, trust.iter=5000, report.freq = 2))


x = x_params#res$config$opt$init
Npar=7;Dpar = length(res$config$beta)+1#length(x)

parDf = data.frame(x)[,rep(1, Npar)]
Sx = seq(-0.5, 0.5, len=Npar) + parDf[Dpar,1]
SxD = Sx[-1] - diff(Sx)/2
parDf[Dpar,] = Sx


res2 = mapply(
  adlaplace::logLikLaplace,
  x = as.list(parDf),
  MoreArgs = list(adFun = ad_fun, config = res$config, deriv=TRUE,
  control = list(report.level = 0, trust.iter=5000)),
  SIMPLIFY=FALSE
  )

Slik = unlist(lapply(res2, "[[", 'logLik'))
Sdet = unlist(lapply(res2, function(xx) xx$hessian$halfLogDet))
dU = do.call(abind::abind, c(lapply(res2, function(xx) as.matrix(xx$extra$dU)), along=3))
uHat = do.call(rbind, lapply(res2, function(xx) xx$opt$solution))
extraDf = do.call(abind::abind, c(lapply(res2, '[[', "deriv"), along=3))
gradMat = do.call(rbind, lapply(res2, '[[', 'grad'))
gradVec = unlist(lapply(res2, function(xx) xx$deriv[Dpar,'dL']))


plot(Sx, Slik)

plot(Sx, gradVec)
lines(SxD, diff(Slik)/diff(Sx), lwd=2, type='o', pch='.')

Du = 1
plot(Sx, uHat[,Du])

plot(Sx, dU[Du,Dpar,])
lines(SxD, diff(uHat[,Du])/diff(Sx))

plot(Sx, Sdet)

plot(Sx, extraDf[Dpar,'dDet',])
lines(SxD, diff(Sdet)/diff(Sx))
```


```{r fit_nt, cache=TRUE}
# devtools::install_github("eborgine/adlaplace")
# devtools::install_github("eborgine/hpolcc")

library("hpolcc")

load("~/research/adlaplace/applications/india/deaths.RData")


res_pm_temp_nt <- hnlm(
  formula = medical ~ dom +
    f(sqrt_pm,
      model = "hiwp", ref_value = 8, p = 2,
      knots = seq(0, 32, by = 2),
      by = "eco_region",
      init = 1e-2,
      lower = 1e-12
    ) +
    f(temp_div10,
      model = "hiwp", ref_value = 25 / 10, p = 3,
      knots = seq(-5, 42.5, by = 2.5) / 10,
      by = "eco_region",
      init = 1e-2,
      lower = 1e-12
    ) +
    f(model = "overdispersion", init = 0.1, parscale = 1),
  data = deaths, # [seq(1, 5e5),],
  cc_design = c("cell", "eco_region", "year_week3_dow"),
  config = list(
    transform_theta = FALSE,
    num_threads = parallel::detectCores(),
    num_groups = 1e4,
    verbose = TRUE
  ),
  control = list(
    maxit = 1000,
    trace = 3,
    REPORT = 1
  ),
  control_inner = list(report.level = 0, trust.iter = 5000),
  for_dev = FALSE
)

saveRDS(res_pm_temp_nt, file = "resPmTempNt.rds")
#invisible(sapply(list.files("~/research/adlaplace/hpolcc/R", pattern = "\\.R$", full.names = TRUE), source))
```


```{r par_table2}
res <- res_pm_temp_nt #readRDS("resPmTempR.rds")
s_var <- names(res$sample$sim)
s_var_names <- c(temp_div10 = "temperature", sqrt_pm = "PM2.5")[s_var]

theta_table = res$parameters$theta[,c("term","model","mle", "init","lower", "parscale", "log_mle")]
theta_table$term = s_var_names[theta_table$term]
theta_table
```

here

```{r optstuf, echo=TRUE}
res_pm_temp_nt$opt
res_pm_temp$opt
```