```{r stuff}
data = readRDS("~/research/india-climate-maternal-study-2025/allData.rds")

data$domInt = as.numeric(format(data$date, '%d'))
data[data$domInt == Hmisc::monthDays(data$date), 'domInt'] = 30
data$dom5 = 1+((data$domInt %% 5) == 0)
data[format(data$date, '%m%d') == '0101', 'dom5'] = 3

#alldat$dom5 = factor(alldat$dom5, labels =c(' ', '5', 'nyd'))

data$dom5 <- factor(data$dom5,
                      levels = c(1, 2, 3),
                      labels = c(' ', '5', 'nyd'),
                      exclude = NULL)


NinStrata = aggregate(data[,'y'], data[,'uniqueStrata'], sum)
colnames(NinStrata) = gsub("^y$", "NinStrata", colnames(NinStrata))
data = merge(data, NinStrata, all=TRUE)

data$temp_value_lagzero = data$temp_value_lag0

res <- hpolcc::hnlm(
  formula= y ~ dom5 + 
  f(temp_value_lagzero, model='iwp',ref_value = 25, p=3, 
      knots = seq(0, 40, by=2.5)), 
  data=data,
  cc_design =  c("cell", "timeStrata"),
  config = list(
    transform_theta = TRUE, 
    boundary_is_random= TRUE,
    dirichlet= TRUE, verbose=TRUE,
    num_threads=parallel::detectCores(), 
    Nclusters = 100*parallel::detectCores(),
    Nsim = 1000
  )
  )

par(mar=c(4,4,0,0), bty='l')
toPlot = 100*(exp(res$sample$global[[1]])-1)
 matplot(
  res$sample$x[[1]], 
  toPlot, type='l', lty=1, col='#00000004', ylim = 100*c(-0.5, 1.5),
    xlab = 'mean temp', ylab='pct rr', xaxs='i'
) 
matlines(
  res$sample$x[[1]], 
  t(apply(toPlot, 1, quantile, prob=c(0.025, 0.975, 0.5))),
  lty=c(2,2,1), col='red'
  )



```


```{r check}
stuff <- hpolcc::hnlm(
  formula= y ~ dom5 + 
  f(temp_value_lagzero, model='iwp',ref_value = 25, p=3, 
      knots = seq(0, 40, by=2.5)), 
  data=data,
  cc_design =  c("cell", "timeStrata"),
  config = list(
    transform_theta = TRUE, 
    boundary_is_random= TRUE,
    dirichlet= TRUE, verbose=TRUE,
    num_threads=parallel::detectCores(), 
    Nclusters = 100*parallel::detectCores(),
    Nsim = 1000
  ), for_debug=TRUE
  )

```
