---
title: "Laplace Approximations with adlaplace"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Laplace Approximations with adlaplace}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


Neg Binoma, $E(y) = \mu$, $\theta$ is size, $1/\sqrt(\theta)$ is sd of Gamma random effect

$$
\begin{aligned}
f(y;\mu,\theta) =  & \log\Gamma(y + r) - \log\Gamma(r) - \log\Gamma(y + 1) 
	+ r \log(\frac{r}{r + \mu})
	+ y \log(\frac{\mu}{r + \mu}) \\
	= &  \log\Gamma(y + r) - \log\Gamma(r) - \log\Gamma(y + 1)  + r \log r - r \log(r + \mu) + y \log(\mu) - y\log(r + \mu)
\end{aligned}
$$

# to do

- add hpp files for a few models in inst (i.e. neg binom)
- put Rinterfaces, rcppexports in inst somehow?  


```{r theData}
Nobs = 1000;Nrandom1=10;Nrandom2=25

set.seed(0)
X = Matrix::Matrix(cbind(1, rbinom(Nobs,1, prob= 0.5)))
AmatList = list(
	Matrix::sparseMatrix(
		i = 1:Nobs,
		j= sample(Nrandom1, Nobs, replace=TRUE)
	),
	Matrix::sparseMatrix(
		i = 1:Nobs,
		j= sample(Nrandom2, Nobs, replace=TRUE)
	)
)
Amat = do.call(cbind, AmatList)
beta = rep(1, ncol(X))
thetaOrig = c(0.1, 0.1, 0.1);theta = log(thetaOrig)
gamma = rnorm(ncol(Amat), sd=rep(thetaOrig[1:2], c(Nrandom1, Nrandom2)))
eta = as.vector(X %*% beta + Amat %*% gamma)
etaT = exp(eta)
Z = rgamma(length(etaT), 0.1^(-2), 0.1^(-2))
c(mean(Z), sd(Z))
y = rpois(length(etaT), etaT*Z)

NperEffect = unlist(lapply(AmatList, ncol))   
#map = rep(seq(0, len=length(NperEffect)), NperEffect)
map = Matrix::sparseMatrix(
	i = seq(0L, len=ncol(Amat)),
	j = rep(seq(0L, len=length(NperEffect)), NperEffect),
	x = 1L,
	index1=FALSE,
	dims = c(ncol(Amat), length(thetaOrig))
	)

data = list(y = y, 
	ATp = as(Matrix::t(Amat), 'dMatrix'),
	XTp = as(Matrix::t(X), 'CsparseMatrix'),
	map = map, 
	Qdiag = rep(1, ncol(Amat)))


config = list(beta = rep(1, nrow(data$XTp)), 
	theta = c(rep(-1, length(NperEffect)), -1), 
	transform_theta=TRUE, 
	gamma = rep(0, nrow(data$ATp)),
	groups = adlaplace::adFun_groups(1000, data$ATp),
	num_threads=parallel::detectCores(),
	verbose=FALSE, package='adlaplace')	
```



model is defined in the file `src/objectiveFunction.cpp`



```{r testDeriv}
adFun = adlaplace::getAdFun(data, modifyList(config, list(verbose=TRUE)))

x = c(config$beta, rep(0.1, length(config$gamma)), config$theta)
adlaplace::jointLogDens(x, adFun)


str(adlaplace::grad(x, adFun, FALSE))
str(adlaplace::grad(x, adFun, TRUE))


Dgroup = ncol(config$groups)+1
str(h1 <- adlaplace::hess(x, adFun, FALSE, Sgroups = Dgroup))
adFun$sparsity[1+Dgroup]
(Shere = 1+seq(
	adFun$hessian$map$outer$p[Dgroup+1],
	adFun$hessian$map$outer$p[Dgroup+2]-1))
adFun$hessians$map$outer$local[Shere]
adFun$hessians$map$outer$global[Shere]
(hseq = which(h1@x != 0))
h1@x[hseq]


str(h2 <- adlaplace::hess(x, adFun, TRUE))

config$num_threads = 2L
bob = adlaplace::innerOptTest(adPack, config)
bob$hessian2 = Matrix::forceSymmetric(
	Matrix::sparseMatrix(i=bob$hessian$i, p=bob$hessian$p, x = bob$hessian$x, index1=FALSE,
	dims = rep(length(bob$hessian$p)-1, 2))
	)
beans = bob$hessian2 + h2  
quantile(beans@x)
```

To Do: 

- create adpack_api, avoid SEXP pointer 
- test innerOpt
- logLik
- third
- adlaplaceExample!



```{r lik}
cache = new.env()
assign('start_gamma', config$start_gamma, cache)


ll0 = adlaplace::logLik(
	x= c(config$beta, config$theta),
	data, config,
	start_gamma = cache$start_gamma,
	adPack = adFunFull,
	deriv=TRUE)
ll0$dL

mle = trustOptim::trust.optim(
	c(config$beta, config$theta),
	adlaplace::outer_fn, adlaplace::outer_gr,
	method='SR1',
	data=data, config=config, cache=cache, adPack = adFunFull,
	control_inner = list(),
	control = list(report.level=4, report.freq=1)
	)
mle$solution
exp(mle$solution[-(1:length(beta))])

```


```{r checkDerivLik, eval=FALSE}

Npar=13;Dpar = 1
x = c(mle$solution[seq(1, len=length(config$beta))], mle$solution[seq(length(config$beta)+1, len=length(config$theta))])
parDf = data.frame(x)[,rep(1, Npar)]
Sx = seq(-0.1, 0.1, len=13) + parDf[Dpar,1]
SxD = Sx[-1] - diff(Sx)/2
parDf[Dpar,] = Sx

Sgamma = seq(length(config$beta)+1, len=length(config$start_gamma))

dens1 = mapply(
  adlaplace::logLik,
  x = as.list(parDf),
  MoreArgs = list(data=data, config=config, deriv=TRUE, adPack = adFunFull),
  SIMPLIFY=FALSE
  )

deriv1 = do.call(abind::abind, c(lapply(lapply(dens1, '[[', "deriv"), '[[', 'deriv'), list(along=3)))
sL = unlist(lapply(dens1, function(xx) xx$inner$minusLogLik))


plot(Sx, sL, #ylim = min(sL)+c(0, 20), 
	type='o');abline(v=x[Dpar])


plot(Sx, deriv1[Dpar,'dL', ], xlab=Dpar)
lines(SxD, diff(sL)/diff(Sx))
abline(v=x[Dpar]);abline(h=0)


sDet = unlist(lapply(dens1, function(xx) xx$inner$halfLogDet))
dDet = diff(sDet)/diff(Sx)
plot(Sx, deriv1[Dpar,'dDet', ], ylim = range(c(dDet, deriv1[Dpar,'dDet', ])))
lines(SxD, dDet)


dens1[[ceiling(length(dens1)/2)]]$deriv
```



log likelihood in R, for debugging

```{r llPlain}
llPlain = function(x, data, config) {
	Nbeta = length(config$beta)
	Ngamma = length(config$start_gamma)
	Ntheta = length(config$theta)

	Sobs = config$groups@i+1

	beta = x[1:Nbeta]
	gamma = x[seq(Nbeta+1, len=Ngamma)]
	theta = x[seq(Nbeta + Ngamma+1, len=Ntheta)]
	if(config$transform_theta) {
		theta = exp(theta)
	}

	eta = as.vector(X[Sobs,] %*% beta + Amat[Sobs,] %*% gamma)
	yHere = data$y[Sobs]

	mu = exp(eta)
	dataPart = sum(dnbinom(
		yHere,
		mu = mu,
		size = theta[length(theta)]^(-2),
		log=TRUE
		))

		r = theta[length(theta)]^(-2)
		loglik_vec1a <-  - r * log(r + mu) + yHere * (log(mu) - log(r + mu))
		loglik_vec1dd <-  - log(r + mu) * (r + yHere) 
		loglik_vec1ee <- yHere * log(mu)
		loglik_vec1b <-  loglik_vec1dd + loglik_vec1ee
		if(any(abs(loglik_vec1a - loglik_vec1b)>1e-6)) {
			cat("stuff")
		}

		loglik_vec2 = lgamma(yHere + r) 
		loglik_vec3 =  - lgamma(yHere + 1) - lgamma(r) + r * log(r)

		dataMapJ = as(data$map, 'TsparseMatrix')
		thetaMap = theta[dataMapJ@j +1L]
		gamma_scaled = gamma / thetaMap
		qpart = 0.5 * sum(gamma_scaled^2 * data$Qdiag)
		qpartDet = sum(log(thetaMap))

		c(random = qpart, 
			randomDet = qpartDet,
		 	obs=-sum(loglik_vec1b) ,
		 	extra=  - sum(loglik_vec2) - sum(loglik_vec3), 
			dd=sum(loglik_vec1dd), ee=sum(loglik_vec1ee), 
			R = -dataPart,
			minusLogLik = -dataPart + qpart + qpartDet)
	}
```



```{r checkThird, eval=FALSE}

adPack = adlaplace::getAdFun(data, modifyList(config, 
	list(verbose=FALSE, num_threads = 1)), inner=FALSE)

ll1 = adlaplace::logLik(
	mle$solution,
	data, config,
	adPack = adPack,
	deriv=TRUE)


newd = adlaplace:::logLikDeriv(
    x = ll1$full_parameters,
    cholHessian=ll1$inner$cholHessian,
    hessian_full = ll1$outer$hessian_full,
    gradient_full = ll1$outer$gradient_full,
    config= modifyList(config, list(verbose=TRUE)),
    adPack = adPack,
    package =  'adlaplace' 
  )

forThird = function(x, ...) {
  adlaplace::hessian(parameters = x, ...)@x
}
hes1 =  numDeriv::jacobian(
  forThird,
  x = ll1$full_parameters,
  adPack = adPack, config=modifyList(config, list(verbose=FALSE))
  )

Hinv = Matrix::crossprod(ll1$deriv$extra$halfH)
Sgamma = seq(length(config$beta)+1, len=length(config$start_gamma))

newTrace = apply(hes1, 2, function(xx) {
	thirdHere = config$hessian_outer
	thirdHere@x = xx
	sum(Matrix::diag(Hinv %*% thirdHere[Sgamma, Sgamma]))
	})

```



```{r derivJointDens, eval=FALSE}
config$gamma = rep(1, length(config$gamma))
x = c(config$beta, config$gamma, config$theta)
adFun = adlaplace::getAdFun(data, modifyList(config, list(verbose=TRUE)))

inner = FALSE
type = c('outer','inner')[1+inner]


Sgamma1 = seq.int(length(config$beta)+1, length.out = length(config$gamma))


Npar=13;Dpar = 3
if(inner) {
	Dpar = match(Dpar, Sgamma1)
}
Dpar0=Dpar-1L

bob = as(adFun$hessians$hessian[[type]], 'TsparseMatrix')
(whichIndex = which(bob@i == Dpar0 & bob@j == Dpar0)-1L)
(whichGlobal = which(adFun$hessians$map[[type]]$global==whichIndex)-1L)

(whichP = mapply(
	function(xx) min(which(adFun$hessian$map[[type]]$p >= xx)),
 	xx = whichGlobal) -1L)



do.call(rbind, adFun$sparsity[[
	whichP[1] 
	]][c('row_hess','col_hess')])
do.call(rbind, adFun$sparsity[[
	whichP[1] 
	]][c('row_hess_inner', 'col_hess_inner')])
	

(Sgroups = whichP-1L)
Sgroups = seq.int(from=0, length.out = length(adFun$sparsity))

#Sgroups = c()


parDf = data.frame(x)[,rep(1, Npar)]
Sx = seq(-0.1, 0.1, len=13) + parDf[Dpar,1]
SxD = Sx[-1] - diff(Sx)/2
parDf[Dpar,] = Sx


dens1 = mapply(
  adlaplace::jointLogDens,
  x = as.list(parDf),
  MoreArgs = list(backendContext = adFun, Sgroups = Sgroups),
  SIMPLIFY=TRUE
  )

plot(Sx, dens1)


grad1 = mapply(
  adlaplace::grad,
  x = as.list(parDf),
  MoreArgs = list(backendContext = adFun, inner=inner, Sgroups = Sgroups),
  SIMPLIFY=TRUE
  )
plot(Sx, grad1[Dpar,])
lines(SxD, diff(dens1)/diff(Sx))


hes1 = mapply(
  adlaplace::hess,
  x = as.list(parDf),
  MoreArgs = list(backendContext = adFun, inner=inner, Sgroups = Sgroups),
  SIMPLIFY=FALSE)

hes2 = do.call(abind::abind, c(
	lapply(hes1, as.matrix), along=3))

gradD = apply(grad1, 1, diff) / mean(diff(Sx))

Dpar2 = dim(hes2)[1]-2
plot(Sx, hes2[Dpar,Dpar2, ], ylab = paste(Dpar, Dpar2),
	ylim = range(hes2[Dpar, Dpar2,], na.rm=TRUE))
lines(SxD, gradD[,Dpar2])
```






