---
title: "GAMM Examples"
author: "Patrick Brown"
date: "`r Sys.Date()`"
format:
  html:
    toc: true
    toc-depth: 3
vignette: >
  %\VignetteIndexEntry{GAMM Examples}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
---

simple examples using gamm as alternative to gam
taken from help files for mgcv::gamm

```{r setup, include=FALSE}
library("Matrix")
library("adlaplace")
```

```{r gamm}
if (requireNamespace("mgcv", quietly = TRUE)) {
  dat <- mgcv::gamSim(6, n = 200, scale = .2, dist = "poisson")
  b2 <- mgcv::gamm(y ~ s(x2),
    family = poisson,
    data = dat, random = list(fac = ~1)
  )
} else {
  data("gamm", package = "adlaplace")
}
plot(b2$gam, pages = 1)
```


```{r collect_terms}
my_formula <-
  f(y, model = "nbinom", lower = 1e-9) ~
  x1 +
  f(x2,
    model = "iwp", p = 2,
    knots = seq(0, 1, len = 11), ref_value = 0.5
  ) +
  f(
    fac,
    model = "iid"
  )

my_formula_2 <-
  nbinom(y, lower = 1e-9) ~
  x1 +
  iwp(
    x2,
    p = 2, knots = seq(0, 1, len = 11), ref_value = 0.5
  ) +
  iid(fac)

my_terms <- collect_terms(
  my_formula,
  verbose = TRUE
)
my_terms_2 <- collect_terms(
  my_formula_2,
  verbose = TRUE
)
```

```{r model_data}
md <- model_data(
  data = dat,
  formula = my_formula
)

config <- list(
  beta = md$data$info$beta$init,
  gamma = rep(0, nrow(md$data$info$gamma)),
  theta = md$data$info$theta$init,
  transform_theta = TRUE,
  shards = adlaplace::ad_shards(
    md$data$A,
    num_shards = 100
  ),
  verbose = TRUE,
  package = "adlaplace"
)
```


```{r ad_fun_create}
ad_fun <- adlaplace::ad_fun(md, config, num_threads = 2L)
```

```{r checkByShard}
shards <- seq.int(from = 0, length.out = adlaplace::n_groups(ad_fun@ptr))
xx <- c(config$beta, config$gamma, config$theta)


by_shard <- mapply(
  adlaplace::joint_log_dens,
  shards = shards,
  MoreArgs = list(x = xx, ad_fun = ad_fun@ptr, negative = FALSE),
  SIMPLIFY = TRUE
)
by_shard[seq(to = length(by_shard), length.out = 5)]
```


```{r log_lik}
res <- adlaplace::log_lik_laplace(
  x = c(config$beta, config$theta),
  ad_fun = ad_fun,
  config = c(config, list(verbose = FALSE)),
  deriv = TRUE
)
res$parameters
res$fval
res$grad
```


```{r trustOptimOuterWrappers}
if (requireNamespace("mgcv", quietly = TRUE)) {
  theta_for_opt <- md$info$theta
  to_transform <- c("init", "lower", "upper")
  theta_for_opt[, to_transform] <- log(theta_for_opt[, to_transform])

  to_keep <- c("init", "lower", "upper", "parscale")

  config$opt <- as.list(
    rbind(
      md$info$beta[, to_keep],
      theta_for_opt[, to_keep]
    )
  )

  cache <- new.env(parent = emptyenv())
  cache$gamma <- rep(0, nrow(md$info$gamma))

  x0 <- config$opt$init

  adlaplace::outer_fn(x = x0, cache = cache, config = config, ad_fun = ad_fun)
  adlaplace::outer_gr(x = x0, cache = cache, config = config, ad_fun = ad_fun)

  outer_fit <- stats::optim(
    par = config$opt$init,
    fn = adlaplace::outer_fn,
    gr = adlaplace::outer_gr,
    method = "L-BFGS-B",
    control = list(
      maxit = 1000,
      trace = 3,
      REPORT = 1
    ),
    lower = config$opt$lower,
    upper = config$opt$upper,
    config = config,
    ad_fun = ad_fun,
    cache = cache
  )

  outer_fit$par
  outer_fit$value
}
```


```{r plot_results}
if (requireNamespace("mgcv", quietly = TRUE)) {
  res <- adlaplace::log_lik_laplace(
    x = outer_fit$par,
    gamma = cache$gamma,
    ad_fun = ad_fun,
    config = config,
    deriv = FALSE
  )

  newx <- data.frame(x2 = seq(0, 1, len = 101))

  sim <- adlaplace::sim_fit(
    x = newx,
    data = md,
    fit = res,
    n = 500L
  )

  matplot(newx$x2, sim, type = "l", col = "#00000010", lty = 1)

  sim_sumzero <- sim - matrix(apply(sim, 2, mean), nrow(sim), ncol(sim), byrow = TRUE)
  matplot(newx$x2, sim_sumzero, type = "l", col = "#00000010", lty = 1)
}
```