// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getAdFun
SEXP getAdFun(Rcpp::List data, Rcpp::List config);
RcppExport SEXP _adlaplace_getAdFun(SEXP dataSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(getAdFun(data, config));
    return rcpp_result_gen;
END_RCPP
}
// jointLogDens
double jointLogDens(SEXP ad_fun, const Rcpp::NumericVector& x, SEXP Sgroups);
RcppExport SEXP _adlaplace_jointLogDens(SEXP ad_funSEXP, SEXP xSEXP, SEXP SgroupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ad_fun(ad_funSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Sgroups(SgroupsSEXP);
    rcpp_result_gen = Rcpp::wrap(jointLogDens(ad_fun, x, Sgroups));
    return rcpp_result_gen;
END_RCPP
}
// grad
Rcpp::NumericVector grad(SEXP ad_fun, const Rcpp::NumericVector& x, bool inner, SEXP Sgroups);
RcppExport SEXP _adlaplace_grad(SEXP ad_funSEXP, SEXP xSEXP, SEXP innerSEXP, SEXP SgroupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ad_fun(ad_funSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type inner(innerSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Sgroups(SgroupsSEXP);
    rcpp_result_gen = Rcpp::wrap(grad(ad_fun, x, inner, Sgroups));
    return rcpp_result_gen;
END_RCPP
}
// hessian
Rcpp::DataFrame hessian(SEXP ad_fun, const Rcpp::NumericVector& x, bool inner, SEXP Sgroups, const bool verbose);
RcppExport SEXP _adlaplace_hessian(SEXP ad_funSEXP, SEXP xSEXP, SEXP innerSEXP, SEXP SgroupsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ad_fun(ad_funSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type inner(innerSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Sgroups(SgroupsSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(hessian(ad_fun, x, inner, Sgroups, verbose));
    return rcpp_result_gen;
END_RCPP
}
// traceHinvT
Rcpp::NumericVector traceHinvT(SEXP ad_fun, const Rcpp::NumericVector& x, const Rcpp::S4& LinvPt, const Rcpp::S4& LinvPtColumns, const int num_threads, SEXP Sgroups);
RcppExport SEXP _adlaplace_traceHinvT(SEXP ad_funSEXP, SEXP xSEXP, SEXP LinvPtSEXP, SEXP LinvPtColumnsSEXP, SEXP num_threadsSEXP, SEXP SgroupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ad_fun(ad_funSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::S4& >::type LinvPt(LinvPtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::S4& >::type LinvPtColumns(LinvPtColumnsSEXP);
    Rcpp::traits::input_parameter< const int >::type num_threads(num_threadsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Sgroups(SgroupsSEXP);
    rcpp_result_gen = Rcpp::wrap(traceHinvT(ad_fun, x, LinvPt, LinvPtColumns, num_threads, Sgroups));
    return rcpp_result_gen;
END_RCPP
}
// hessianMapC
Rcpp::List hessianMapC(const Rcpp::List& sparsity_list, const int Nbeta, const int Ngamma, const int Ntheta);
RcppExport SEXP _adlaplace_hessianMapC(SEXP sparsity_listSEXP, SEXP NbetaSEXP, SEXP NgammaSEXP, SEXP NthetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type sparsity_list(sparsity_listSEXP);
    Rcpp::traits::input_parameter< const int >::type Nbeta(NbetaSEXP);
    Rcpp::traits::input_parameter< const int >::type Ngamma(NgammaSEXP);
    Rcpp::traits::input_parameter< const int >::type Ntheta(NthetaSEXP);
    rcpp_result_gen = Rcpp::wrap(hessianMapC(sparsity_list, Nbeta, Ngamma, Ntheta));
    return rcpp_result_gen;
END_RCPP
}
// all_derivs
Rcpp::List all_derivs(const Rcpp::NumericVector& x, SEXP adFun, const Rcpp::List& config);
RcppExport SEXP _adlaplace_all_derivs(SEXP xSEXP, SEXP adFunSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type adFun(adFunSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(all_derivs(x, adFun, config));
    return rcpp_result_gen;
END_RCPP
}
// inner_opt
Rcpp::List inner_opt(const Rcpp::NumericVector parameters, const Rcpp::NumericVector gamma, const Rcpp::List& config, const Rcpp::List& control, SEXP adFun);
RcppExport SEXP _adlaplace_inner_opt(SEXP parametersSEXP, SEXP gammaSEXP, SEXP configSEXP, SEXP controlSEXP, SEXP adFunSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type control(controlSEXP);
    Rcpp::traits::input_parameter< SEXP >::type adFun(adFunSEXP);
    rcpp_result_gen = Rcpp::wrap(inner_opt(parameters, gamma, config, control, adFun));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_adlaplace_getAdFun", (DL_FUNC) &_adlaplace_getAdFun, 2},
    {"_adlaplace_jointLogDens", (DL_FUNC) &_adlaplace_jointLogDens, 3},
    {"_adlaplace_grad", (DL_FUNC) &_adlaplace_grad, 4},
    {"_adlaplace_hessian", (DL_FUNC) &_adlaplace_hessian, 5},
    {"_adlaplace_traceHinvT", (DL_FUNC) &_adlaplace_traceHinvT, 6},
    {"_adlaplace_hessianMapC", (DL_FUNC) &_adlaplace_hessianMapC, 4},
    {"_adlaplace_all_derivs", (DL_FUNC) &_adlaplace_all_derivs, 3},
    {"_adlaplace_inner_opt", (DL_FUNC) &_adlaplace_inner_opt, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_adlaplace(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
