// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// create_ad_fun_random_fem_ssq_2
SEXP create_ad_fun_random_fem_ssq_2(SEXP model, Rcpp::List config);
RcppExport SEXP _adlaplaceGrf_create_ad_fun_random_fem_ssq_2(SEXP modelSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(create_ad_fun_random_fem_ssq_2(model, config));
    return rcpp_result_gen;
END_RCPP
}
// create_ad_fun_random_fem_ssq_3
SEXP create_ad_fun_random_fem_ssq_3(SEXP model, Rcpp::List config);
RcppExport SEXP _adlaplaceGrf_create_ad_fun_random_fem_ssq_3(SEXP modelSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(create_ad_fun_random_fem_ssq_3(model, config));
    return rcpp_result_gen;
END_RCPP
}
// get_ad_fun_raw_parameters
SEXP get_ad_fun_raw_parameters(SEXP model, Rcpp::List config, std::string name);
RcppExport SEXP _adlaplaceGrf_get_ad_fun_raw_parameters(SEXP modelSEXP, SEXP configSEXP, SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model(modelSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type config(configSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    rcpp_result_gen = Rcpp::wrap(get_ad_fun_raw_parameters(model, config, name));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_adlaplaceGrf_create_ad_fun_random_fem_ssq_2", (DL_FUNC) &_adlaplaceGrf_create_ad_fun_random_fem_ssq_2, 2},
    {"_adlaplaceGrf_create_ad_fun_random_fem_ssq_3", (DL_FUNC) &_adlaplaceGrf_create_ad_fun_random_fem_ssq_3, 2},
    {"_adlaplaceGrf_get_ad_fun_raw_parameters", (DL_FUNC) &_adlaplaceGrf_get_ad_fun_raw_parameters, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_adlaplaceGrf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
