// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getAdFun
SEXP getAdFun(Rcpp::NumericVector x, const Rcpp::List data, const Rcpp::List config);
RcppExport SEXP _hpolcc_getAdFun(SEXP xSEXP, SEXP dataSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(getAdFun(x, data, config));
    return rcpp_result_gen;
END_RCPP
}
// traceHinvT
Rcpp::NumericVector traceHinvT(const Rcpp::NumericVector parameters, const Rcpp::S4& LinvPt, const Rcpp::List data, const Rcpp::List config, SEXP adFun);
RcppExport SEXP _hpolcc_traceHinvT(SEXP parametersSEXP, SEXP LinvPtSEXP, SEXP dataSEXP, SEXP configSEXP, SEXP adFunSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::S4& >::type LinvPt(LinvPtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type config(configSEXP);
    Rcpp::traits::input_parameter< SEXP >::type adFun(adFunSEXP);
    rcpp_result_gen = Rcpp::wrap(traceHinvT(parameters, LinvPt, data, config, adFun));
    return rcpp_result_gen;
END_RCPP
}
// thirdStrata
Rcpp::List thirdStrata(const Rcpp::NumericVector parameters, const Rcpp::List data, const Rcpp::List config, SEXP adFun);
RcppExport SEXP _hpolcc_thirdStrata(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP, SEXP adFunSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type config(configSEXP);
    Rcpp::traits::input_parameter< SEXP >::type adFun(adFunSEXP);
    rcpp_result_gen = Rcpp::wrap(thirdStrata(parameters, data, config, adFun));
    return rcpp_result_gen;
END_RCPP
}
// jointLogDens
double jointLogDens(Rcpp::NumericVector parameters, const Rcpp::List data, const Rcpp::List config, SEXP adFun);
RcppExport SEXP _hpolcc_jointLogDens(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP, SEXP adFunSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type config(configSEXP);
    Rcpp::traits::input_parameter< SEXP >::type adFun(adFunSEXP);
    rcpp_result_gen = Rcpp::wrap(jointLogDens(parameters, data, config, adFun));
    return rcpp_result_gen;
END_RCPP
}
// grad
Rcpp::NumericVector grad(const Rcpp::NumericVector parameters, const Rcpp::List& data, const Rcpp::List& config, SEXP adFun);
RcppExport SEXP _hpolcc_grad(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP, SEXP adFunSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    Rcpp::traits::input_parameter< SEXP >::type adFun(adFunSEXP);
    rcpp_result_gen = Rcpp::wrap(grad(parameters, data, config, adFun));
    return rcpp_result_gen;
END_RCPP
}
// hessian
Rcpp::RObject hessian(const Rcpp::NumericVector parameters, const Rcpp::List& data, const Rcpp::List& config, SEXP adFun);
RcppExport SEXP _hpolcc_hessian(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP, SEXP adFunSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    Rcpp::traits::input_parameter< SEXP >::type adFun(adFunSEXP);
    rcpp_result_gen = Rcpp::wrap(hessian(parameters, data, config, adFun));
    return rcpp_result_gen;
END_RCPP
}
// hessianQdense
Rcpp::NumericMatrix hessianQdense(const Rcpp::NumericVector parameters, const Rcpp::List& data, const Rcpp::List& config);
RcppExport SEXP _hpolcc_hessianQdense(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(hessianQdense(parameters, data, config));
    return rcpp_result_gen;
END_RCPP
}
// gradDense
Rcpp::NumericVector gradDense(const Rcpp::NumericVector parameters, const Rcpp::List& data, const Rcpp::List& config, SEXP adFun);
RcppExport SEXP _hpolcc_gradDense(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP, SEXP adFunSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    Rcpp::traits::input_parameter< SEXP >::type adFun(adFunSEXP);
    rcpp_result_gen = Rcpp::wrap(gradDense(parameters, data, config, adFun));
    return rcpp_result_gen;
END_RCPP
}
// hessianDense
Rcpp::NumericMatrix hessianDense(const Rcpp::NumericVector parameters, const Rcpp::List& data, const Rcpp::List& config, SEXP adFun);
RcppExport SEXP _hpolcc_hessianDense(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP, SEXP adFunSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    Rcpp::traits::input_parameter< SEXP >::type adFun(adFunSEXP);
    rcpp_result_gen = Rcpp::wrap(hessianDense(parameters, data, config, adFun));
    return rcpp_result_gen;
END_RCPP
}
// hessianQdenseLogical
Rcpp::LogicalMatrix hessianQdenseLogical(const Rcpp::NumericVector parameters, const Rcpp::List& data, const Rcpp::List& config);
RcppExport SEXP _hpolcc_hessianQdenseLogical(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(hessianQdenseLogical(parameters, data, config));
    return rcpp_result_gen;
END_RCPP
}
// hessianDenseLogical
Rcpp::LogicalMatrix hessianDenseLogical(const Rcpp::NumericVector parameters, const Rcpp::List& data, const Rcpp::List& config);
RcppExport SEXP _hpolcc_hessianDenseLogical(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(hessianDenseLogical(parameters, data, config));
    return rcpp_result_gen;
END_RCPP
}
// gradQLogical
Rcpp::LogicalVector gradQLogical(const Rcpp::NumericVector parameters, const Rcpp::List& data, const Rcpp::List& config);
RcppExport SEXP _hpolcc_gradQLogical(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(gradQLogical(parameters, data, config));
    return rcpp_result_gen;
END_RCPP
}
// gradLogical
Rcpp::RObject gradLogical(const Rcpp::NumericVector parameters, const Rcpp::List& data, const Rcpp::List& config);
RcppExport SEXP _hpolcc_gradLogical(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(gradLogical(parameters, data, config));
    return rcpp_result_gen;
END_RCPP
}
// jointLogDensDense
double jointLogDensDense(Rcpp::NumericVector parameters, const Rcpp::List data, const Rcpp::List config, SEXP adFun);
RcppExport SEXP _hpolcc_jointLogDensDense(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP, SEXP adFunSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type config(configSEXP);
    Rcpp::traits::input_parameter< SEXP >::type adFun(adFunSEXP);
    rcpp_result_gen = Rcpp::wrap(jointLogDensDense(parameters, data, config, adFun));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hpolcc_getAdFun", (DL_FUNC) &_hpolcc_getAdFun, 3},
    {"_hpolcc_traceHinvT", (DL_FUNC) &_hpolcc_traceHinvT, 5},
    {"_hpolcc_thirdStrata", (DL_FUNC) &_hpolcc_thirdStrata, 4},
    {"_hpolcc_jointLogDens", (DL_FUNC) &_hpolcc_jointLogDens, 4},
    {"_hpolcc_grad", (DL_FUNC) &_hpolcc_grad, 4},
    {"_hpolcc_hessian", (DL_FUNC) &_hpolcc_hessian, 4},
    {"_hpolcc_hessianQdense", (DL_FUNC) &_hpolcc_hessianQdense, 3},
    {"_hpolcc_gradDense", (DL_FUNC) &_hpolcc_gradDense, 4},
    {"_hpolcc_hessianDense", (DL_FUNC) &_hpolcc_hessianDense, 4},
    {"_hpolcc_hessianQdenseLogical", (DL_FUNC) &_hpolcc_hessianQdenseLogical, 3},
    {"_hpolcc_hessianDenseLogical", (DL_FUNC) &_hpolcc_hessianDenseLogical, 3},
    {"_hpolcc_gradQLogical", (DL_FUNC) &_hpolcc_gradQLogical, 3},
    {"_hpolcc_gradLogical", (DL_FUNC) &_hpolcc_gradLogical, 3},
    {"_hpolcc_jointLogDensDense", (DL_FUNC) &_hpolcc_jointLogDensDense, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_hpolcc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
