// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// thirdDiagonalsStrata
Rcpp::List thirdDiagonalsStrata(const Rcpp::NumericVector parameters, const Rcpp::List data, const Rcpp::List config);
RcppExport SEXP _hpolcc_thirdDiagonalsStrata(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(thirdDiagonalsStrata(parameters, data, config));
    return rcpp_result_gen;
END_RCPP
}
// thirdOffDiagonalsStrata
Rcpp::List thirdOffDiagonalsStrata(const Rcpp::NumericVector parameters, const Rcpp::List data, const Rcpp::List config);
RcppExport SEXP _hpolcc_thirdOffDiagonalsStrata(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(thirdOffDiagonalsStrata(parameters, data, config));
    return rcpp_result_gen;
END_RCPP
}
// getAdfun
SEXP getAdfun(Rcpp::NumericVector x, const Rcpp::List data, const Rcpp::List config);
RcppExport SEXP _hpolcc_getAdfun(SEXP xSEXP, SEXP dataSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(getAdfun(x, data, config));
    return rcpp_result_gen;
END_RCPP
}
// jointLogDens
double jointLogDens(Rcpp::NumericVector x, const Rcpp::List data, const Rcpp::List config, SEXP adfun);
RcppExport SEXP _hpolcc_jointLogDens(SEXP xSEXP, SEXP dataSEXP, SEXP configSEXP, SEXP adfunSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List >::type config(configSEXP);
    Rcpp::traits::input_parameter< SEXP >::type adfun(adfunSEXP);
    rcpp_result_gen = Rcpp::wrap(jointLogDens(x, data, config, adfun));
    return rcpp_result_gen;
END_RCPP
}
// grad
Rcpp::NumericVector grad(const Rcpp::NumericVector parameters, const Rcpp::List& data, const Rcpp::List& config, SEXP adfun);
RcppExport SEXP _hpolcc_grad(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP, SEXP adfunSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    Rcpp::traits::input_parameter< SEXP >::type adfun(adfunSEXP);
    rcpp_result_gen = Rcpp::wrap(grad(parameters, data, config, adfun));
    return rcpp_result_gen;
END_RCPP
}
// hessian
Rcpp::S4 hessian(const Rcpp::NumericVector parameters, const Rcpp::List& data, const Rcpp::List& config, SEXP adfun);
RcppExport SEXP _hpolcc_hessian(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP, SEXP adfunSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    Rcpp::traits::input_parameter< SEXP >::type adfun(adfunSEXP);
    rcpp_result_gen = Rcpp::wrap(hessian(parameters, data, config, adfun));
    return rcpp_result_gen;
END_RCPP
}
// hessianQdense
Rcpp::NumericMatrix hessianQdense(const Rcpp::NumericVector parameters, const Rcpp::List& data, const Rcpp::List& config);
RcppExport SEXP _hpolcc_hessianQdense(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(hessianQdense(parameters, data, config));
    return rcpp_result_gen;
END_RCPP
}
// hessianDense
Rcpp::NumericMatrix hessianDense(const Rcpp::NumericVector parameters, const Rcpp::List& data, const Rcpp::List& config);
RcppExport SEXP _hpolcc_hessianDense(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(hessianDense(parameters, data, config));
    return rcpp_result_gen;
END_RCPP
}
// hessianDenseLogical
Rcpp::LogicalMatrix hessianDenseLogical(const Rcpp::NumericVector parameters, const Rcpp::List& data, const Rcpp::List& config);
RcppExport SEXP _hpolcc_hessianDenseLogical(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(hessianDenseLogical(parameters, data, config));
    return rcpp_result_gen;
END_RCPP
}
// gradLogical
Rcpp::LogicalMatrix gradLogical(const Rcpp::NumericVector parameters, const Rcpp::List& data, const Rcpp::List& config);
RcppExport SEXP _hpolcc_gradLogical(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(gradLogical(parameters, data, config));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hpolcc_thirdDiagonalsStrata", (DL_FUNC) &_hpolcc_thirdDiagonalsStrata, 3},
    {"_hpolcc_thirdOffDiagonalsStrata", (DL_FUNC) &_hpolcc_thirdOffDiagonalsStrata, 3},
    {"_hpolcc_getAdfun", (DL_FUNC) &_hpolcc_getAdfun, 3},
    {"_hpolcc_jointLogDens", (DL_FUNC) &_hpolcc_jointLogDens, 4},
    {"_hpolcc_grad", (DL_FUNC) &_hpolcc_grad, 4},
    {"_hpolcc_hessian", (DL_FUNC) &_hpolcc_hessian, 4},
    {"_hpolcc_hessianQdense", (DL_FUNC) &_hpolcc_hessianQdense, 3},
    {"_hpolcc_hessianDense", (DL_FUNC) &_hpolcc_hessianDense, 3},
    {"_hpolcc_hessianDenseLogical", (DL_FUNC) &_hpolcc_hessianDenseLogical, 3},
    {"_hpolcc_gradLogical", (DL_FUNC) &_hpolcc_gradLogical, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_hpolcc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
