// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// test3
Rcpp::List test3(Rcpp::NumericVector X, Rcpp::NumericVector U, Rcpp::NumericVector W);
RcppExport SEXP _hpolcc_test3(SEXP XSEXP, SEXP USEXP, SEXP WSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type U(USEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type W(WSEXP);
    rcpp_result_gen = Rcpp::wrap(test3(X, U, W));
    return rcpp_result_gen;
END_RCPP
}
// derivForLaplace
Rcpp::List derivForLaplace(Rcpp::NumericVector parameters, Rcpp::List data, Rcpp::List config);
RcppExport SEXP _hpolcc_derivForLaplace(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(derivForLaplace(parameters, data, config));
    return rcpp_result_gen;
END_RCPP
}
// objectiveFunctionC
Rcpp::List objectiveFunctionC(Rcpp::NumericVector parameters, Rcpp::List data, Rcpp::List config);
RcppExport SEXP _hpolcc_objectiveFunctionC(SEXP parametersSEXP, SEXP dataSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(objectiveFunctionC(parameters, data, config));
    return rcpp_result_gen;
END_RCPP
}
// lgamma_forward_deriv
double lgamma_forward_deriv(double x, int order);
RcppExport SEXP _hpolcc_lgamma_forward_deriv(SEXP xSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    rcpp_result_gen = Rcpp::wrap(lgamma_forward_deriv(x, order));
    return rcpp_result_gen;
END_RCPP
}
// lgamma_reverse_deriv
double lgamma_reverse_deriv(double x, int order);
RcppExport SEXP _hpolcc_lgamma_reverse_deriv(SEXP xSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    rcpp_result_gen = Rcpp::wrap(lgamma_reverse_deriv(x, order));
    return rcpp_result_gen;
END_RCPP
}
// logspaceadd_forward_deriv
Rcpp::NumericMatrix logspaceadd_forward_deriv(Rcpp::NumericVector x, int order);
RcppExport SEXP _hpolcc_logspaceadd_forward_deriv(SEXP xSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    rcpp_result_gen = Rcpp::wrap(logspaceadd_forward_deriv(x, order));
    return rcpp_result_gen;
END_RCPP
}
// logspaceadd_inbuilt_deriv
Rcpp::NumericVector logspaceadd_inbuilt_deriv(Rcpp::NumericVector x, int order);
RcppExport SEXP _hpolcc_logspaceadd_inbuilt_deriv(SEXP xSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type order(orderSEXP);
    rcpp_result_gen = Rcpp::wrap(logspaceadd_inbuilt_deriv(x, order));
    return rcpp_result_gen;
END_RCPP
}
// testAddGammaR
Rcpp::List testAddGammaR(Rcpp::NumericVector parameters);
RcppExport SEXP _hpolcc_testAddGammaR(SEXP parametersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type parameters(parametersSEXP);
    rcpp_result_gen = Rcpp::wrap(testAddGammaR(parameters));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hpolcc_test3", (DL_FUNC) &_hpolcc_test3, 3},
    {"_hpolcc_derivForLaplace", (DL_FUNC) &_hpolcc_derivForLaplace, 3},
    {"_hpolcc_objectiveFunctionC", (DL_FUNC) &_hpolcc_objectiveFunctionC, 3},
    {"_hpolcc_lgamma_forward_deriv", (DL_FUNC) &_hpolcc_lgamma_forward_deriv, 2},
    {"_hpolcc_lgamma_reverse_deriv", (DL_FUNC) &_hpolcc_lgamma_reverse_deriv, 2},
    {"_hpolcc_logspaceadd_forward_deriv", (DL_FUNC) &_hpolcc_logspaceadd_forward_deriv, 2},
    {"_hpolcc_logspaceadd_inbuilt_deriv", (DL_FUNC) &_hpolcc_logspaceadd_inbuilt_deriv, 2},
    {"_hpolcc_testAddGammaR", (DL_FUNC) &_hpolcc_testAddGammaR, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_hpolcc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
