// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pmvn_cpp
Rcpp::List pmvn_cpp(Rcpp::NumericVector upper, Rcpp::NumericVector lower, Rcpp::NumericVector mean, Rcpp::NumericMatrix sigma, int n_points, int n_shifts, unsigned int seed);
RcppExport SEXP _admvn_pmvn_cpp(SEXP upperSEXP, SEXP lowerSEXP, SEXP meanSEXP, SEXP sigmaSEXP, SEXP n_pointsSEXP, SEXP n_shiftsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type n_points(n_pointsSEXP);
    Rcpp::traits::input_parameter< int >::type n_shifts(n_shiftsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pmvn_cpp(upper, lower, mean, sigma, n_points, n_shifts, seed));
    return rcpp_result_gen;
END_RCPP
}
// pmvn_fun_create_cpp
SEXP pmvn_fun_create_cpp(Rcpp::NumericVector lower, Rcpp::NumericVector mean, Rcpp::NumericMatrix sigma, int n_points, int n_shifts, unsigned int seed);
RcppExport SEXP _admvn_pmvn_fun_create_cpp(SEXP lowerSEXP, SEXP meanSEXP, SEXP sigmaSEXP, SEXP n_pointsSEXP, SEXP n_shiftsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type n_points(n_pointsSEXP);
    Rcpp::traits::input_parameter< int >::type n_shifts(n_shiftsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pmvn_fun_create_cpp(lower, mean, sigma, n_points, n_shifts, seed));
    return rcpp_result_gen;
END_RCPP
}
// pmvn_fun_eval_cpp
Rcpp::List pmvn_fun_eval_cpp(SEXP ptr, Rcpp::NumericVector upper);
RcppExport SEXP _admvn_pmvn_fun_eval_cpp(SEXP ptrSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(pmvn_fun_eval_cpp(ptr, upper));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_admvn_pmvn_cpp", (DL_FUNC) &_admvn_pmvn_cpp, 7},
    {"_admvn_pmvn_fun_create_cpp", (DL_FUNC) &_admvn_pmvn_fun_create_cpp, 6},
    {"_admvn_pmvn_fun_eval_cpp", (DL_FUNC) &_admvn_pmvn_fun_eval_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_admvn(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
