// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pmvn_cpp
Rcpp::List pmvn_cpp(Rcpp::NumericVector upper, Rcpp::NumericVector lower, Rcpp::NumericVector mean, Rcpp::NumericMatrix sigma, int n_points, int n_shifts, unsigned int seed);
RcppExport SEXP _admvn_pmvn_cpp(SEXP upperSEXP, SEXP lowerSEXP, SEXP meanSEXP, SEXP sigmaSEXP, SEXP n_pointsSEXP, SEXP n_shiftsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type n_points(n_pointsSEXP);
    Rcpp::traits::input_parameter< int >::type n_shifts(n_shiftsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pmvn_cpp(upper, lower, mean, sigma, n_points, n_shifts, seed));
    return rcpp_result_gen;
END_RCPP
}
// pack_genz_ch_cpp
Rcpp::List pack_genz_ch_cpp(Rcpp::NumericMatrix sigma, Rcpp::IntegerVector perm);
RcppExport SEXP _admvn_pack_genz_ch_cpp(SEXP sigmaSEXP, SEXP permSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type perm(permSEXP);
    rcpp_result_gen = Rcpp::wrap(pack_genz_ch_cpp(sigma, perm));
    return rcpp_result_gen;
END_RCPP
}
// pmvn_fun_create_cpp
SEXP pmvn_fun_create_cpp(Rcpp::NumericVector lower, Rcpp::NumericVector mean, Rcpp::NumericMatrix sigma, Rcpp::Nullable<Rcpp::NumericVector> upper_seed, int n_points, int n_shifts, unsigned int seed);
RcppExport SEXP _admvn_pmvn_fun_create_cpp(SEXP lowerSEXP, SEXP meanSEXP, SEXP sigmaSEXP, SEXP upper_seedSEXP, SEXP n_pointsSEXP, SEXP n_shiftsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type upper_seed(upper_seedSEXP);
    Rcpp::traits::input_parameter< int >::type n_points(n_pointsSEXP);
    Rcpp::traits::input_parameter< int >::type n_shifts(n_shiftsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(pmvn_fun_create_cpp(lower, mean, sigma, upper_seed, n_points, n_shifts, seed));
    return rcpp_result_gen;
END_RCPP
}
// pmvn_fun_perm_cpp
Rcpp::IntegerVector pmvn_fun_perm_cpp(SEXP ptr);
RcppExport SEXP _admvn_pmvn_fun_perm_cpp(SEXP ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(pmvn_fun_perm_cpp(ptr));
    return rcpp_result_gen;
END_RCPP
}
// pmvn_fun_eval_cpp
Rcpp::List pmvn_fun_eval_cpp(SEXP ptr, Rcpp::NumericVector upper, Rcpp::Nullable<Rcpp::NumericVector> mean, Rcpp::Nullable<Rcpp::NumericMatrix> sigma, bool inner);
RcppExport SEXP _admvn_pmvn_fun_eval_cpp(SEXP ptrSEXP, SEXP upperSEXP, SEXP meanSEXP, SEXP sigmaSEXP, SEXP innerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< bool >::type inner(innerSEXP);
    rcpp_result_gen = Rcpp::wrap(pmvn_fun_eval_cpp(ptr, upper, mean, sigma, inner));
    return rcpp_result_gen;
END_RCPP
}
// dsun_cpp
Rcpp::List dsun_cpp(Rcpp::NumericMatrix x, Rcpp::NumericVector par, bool log_scale, int deriv, int n_points, int n_shifts, unsigned int seed, int n_threads);
RcppExport SEXP _admvn_dsun_cpp(SEXP xSEXP, SEXP parSEXP, SEXP log_scaleSEXP, SEXP derivSEXP, SEXP n_pointsSEXP, SEXP n_shiftsSEXP, SEXP seedSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type par(parSEXP);
    Rcpp::traits::input_parameter< bool >::type log_scale(log_scaleSEXP);
    Rcpp::traits::input_parameter< int >::type deriv(derivSEXP);
    Rcpp::traits::input_parameter< int >::type n_points(n_pointsSEXP);
    Rcpp::traits::input_parameter< int >::type n_shifts(n_shiftsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(dsun_cpp(x, par, log_scale, deriv, n_points, n_shifts, seed, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// dsun_fun_create_cpp
SEXP dsun_fun_create_cpp(Rcpp::NumericMatrix x, Rcpp::NumericVector par_seed, int n_points, int n_shifts, unsigned int seed, int n_threads);
RcppExport SEXP _admvn_dsun_fun_create_cpp(SEXP xSEXP, SEXP par_seedSEXP, SEXP n_pointsSEXP, SEXP n_shiftsSEXP, SEXP seedSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type par_seed(par_seedSEXP);
    Rcpp::traits::input_parameter< int >::type n_points(n_pointsSEXP);
    Rcpp::traits::input_parameter< int >::type n_shifts(n_shiftsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(dsun_fun_create_cpp(x, par_seed, n_points, n_shifts, seed, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// dsun_fun_eval_cpp
Rcpp::List dsun_fun_eval_cpp(SEXP ptr, Rcpp::Nullable<Rcpp::NumericVector> par, bool log_scale, int deriv, int n_threads);
RcppExport SEXP _admvn_dsun_fun_eval_cpp(SEXP ptrSEXP, SEXP parSEXP, SEXP log_scaleSEXP, SEXP derivSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type par(parSEXP);
    Rcpp::traits::input_parameter< bool >::type log_scale(log_scaleSEXP);
    Rcpp::traits::input_parameter< int >::type deriv(derivSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(dsun_fun_eval_cpp(ptr, par, log_scale, deriv, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// dsun_n_threads_default_cpp
int dsun_n_threads_default_cpp();
RcppExport SEXP _admvn_dsun_n_threads_default_cpp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(dsun_n_threads_default_cpp());
    return rcpp_result_gen;
END_RCPP
}
// sun_mle_cpp
Rcpp::List sun_mle_cpp(SEXP ptr, Rcpp::NumericVector start, Rcpp::List control, int n_threads);
RcppExport SEXP _admvn_sun_mle_cpp(SEXP ptrSEXP, SEXP startSEXP, SEXP controlSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type start(startSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control(controlSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(sun_mle_cpp(ptr, start, control, n_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_admvn_pmvn_cpp", (DL_FUNC) &_admvn_pmvn_cpp, 7},
    {"_admvn_pack_genz_ch_cpp", (DL_FUNC) &_admvn_pack_genz_ch_cpp, 2},
    {"_admvn_pmvn_fun_create_cpp", (DL_FUNC) &_admvn_pmvn_fun_create_cpp, 7},
    {"_admvn_pmvn_fun_perm_cpp", (DL_FUNC) &_admvn_pmvn_fun_perm_cpp, 1},
    {"_admvn_pmvn_fun_eval_cpp", (DL_FUNC) &_admvn_pmvn_fun_eval_cpp, 5},
    {"_admvn_dsun_cpp", (DL_FUNC) &_admvn_dsun_cpp, 8},
    {"_admvn_dsun_fun_create_cpp", (DL_FUNC) &_admvn_dsun_fun_create_cpp, 6},
    {"_admvn_dsun_fun_eval_cpp", (DL_FUNC) &_admvn_dsun_fun_eval_cpp, 5},
    {"_admvn_dsun_n_threads_default_cpp", (DL_FUNC) &_admvn_dsun_n_threads_default_cpp, 0},
    {"_admvn_sun_mle_cpp", (DL_FUNC) &_admvn_sun_mle_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_admvn(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
