# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Low-level C++ entry points (Rcpp exports)
#'
#' @param data An R list containing model data and matrices required by the AD
#'   construction. Required fields depend on the model (see vignette).
#' @param config An R list of configuration options (e.g., parameter vectors,
#'   sparsity options, threading options).
#' @param inner Logical; if TRUE, build the inner AD function; otherwise build
#'   the outer AD function.
#'
#' @param parameters Numeric vector of parameters for the requested operation
#'   (e.g., inner optimization or trace calculation). Interpretation depends on
#'   the backend/model.
#' @param control Control list for the optimizer (e.g., trust region settings,
#'   tolerances, max iterations). Used by `inner_opt()`.
#' @param adPackFull,adPack Optional external pointer (`externalptr`) returned by
#'   `getAdFun()`. If provided, reuse cached AD objects / sparsity structures.
#'
#' @param LinvPt,LinvPtColumns Sparse matrix objects (S4, typically from Matrix)
#'   used by `traceHinvT()`; see package documentation/vignette for required
#'   classes and dimensions.
#'
#' @return `getAdFun()` returns an external pointer (`externalptr`) to an
#'   internal AD object. 
#'
#'
#' @details
#' The returned pointer is not human-readable and should not be modified.
#' It may hold substantial memory (tapes, sparsity patterns, caches). Use
#' package-level functions to manage lifecycle and computation.
#'
#' @rdname adlaplace_cpp
#' @export
getAdFun <- function(data, config, inner = FALSE) {
    .Call(`_adlaplaceExample_getAdFun`, data, config, inner)
}

#' @rdname adlaplace_cpp
#' @export
inner_opt <- function(parameters, data, control, config, adPackFull = NULL) {
    .Call(`_adlaplaceExample_inner_opt`, parameters, data, control, config, adPackFull)
}

#' @rdname adlaplace_cpp
#' @export
inner_opt_adpack <- function(parameters, adPack, control, config, adPackFull = NULL) {
    .Call(`_adlaplaceExample_inner_opt_adpack`, parameters, adPack, control, config, adPackFull)
}

#' @rdname adlaplace_cpp
#' @export
traceHinvT <- function(parameters, LinvPt, LinvPtColumns, config, adPack = NULL) {
    .Call(`_adlaplaceExample_traceHinvT`, parameters, LinvPt, LinvPtColumns, config, adPack)
}

#' @rdname adlaplace_cpp
#' @export
sparsity <- function(data, config) {
    .Call(`_adlaplaceExample_sparsity`, data, config)
}

#' Joint log-density and derivatives
#'
#' Compute the joint log-density of a hierarchical model and its first- and
#' second-order derivatives using automatic differentiation.  
#'
#' These functions are low-level computational backends intended for deugging.
#' They operate on a vector of parameters and
#' a pre-constructed automatic differentiation object (`adPack`).
#'
#' @param parameters Numeric vector of model parameters. The ordering must
#'   match the structure expected by the automatic differentiation object.
#' @param adPack An external pointer (SEXP) to an automatic differentiation
#'   object created by \code{getAdFun()}.
#' @param config A list of configuration options controlling model structure
#'   and computation.
#'
#' @return
#' \describe{
#'   \item{\code{jointLogDens()}}{A scalar numeric value giving the joint
#'     log-density.}
#'   \item{\code{jointLogDensNoAdfun()}}{As above, but takes data rather than adPack.}
#'   \item{\code{grad()}}{A numeric vector giving the gradient of the joint
#'     log-density with respect to \code{parameters}.}
#'   \item{\code{hessian()}}{A sparse symmetric matrix (as a
#'     \code{dgCMatrix}) giving the Hessian of the joint log-density.}
#' }
#'
#' @details
#' These functions rely on CppAD-based automatic differentiation. The
#' \code{adPack} object encapsulates the taped computation graph and must be
#' compatible with the supplied \code{parameters} and \code{config}.
#'
#' Users should generally call higher-level R wrappers rather than invoking
#' these functions directly.
#'
#' @seealso \code{\link{getAdFun}}, \code{\link{logLik}}
#'
#' @name jointLogDens
#' @rdname jointLogDens
#' @export
jointLogDens <- function(parameters, adPack, config) {
    .Call(`_adlaplaceExample_jointLogDens`, parameters, adPack, config)
}

#' @param data List of data objects used to construct the AD function.
#' @rdname jointLogDens
#' @export
jointLogDensNoAdfun <- function(parameters, data, config) {
    .Call(`_adlaplaceExample_jointLogDensNoAdfun`, parameters, data, config)
}

#' @rdname jointLogDens
#' @export
grad <- function(parameters, adPack, config) {
    .Call(`_adlaplaceExample_grad`, parameters, adPack, config)
}

#' @rdname jointLogDens
#' @export
hessian <- function(parameters, adPack, config) {
    .Call(`_adlaplaceExample_hessian`, parameters, adPack, config)
}

