// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// register_example_densities
void register_example_densities();
RcppExport SEXP _adlaplaceExample_register_example_densities() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    register_example_densities();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_adlaplaceExample_register_example_densities", (DL_FUNC) &_adlaplaceExample_register_example_densities, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_adlaplaceExample(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
