// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getAdFun
Rcpp::List getAdFun(Rcpp::List data, Rcpp::List config);
RcppExport SEXP _adlaplaceExample_getAdFun(SEXP dataSEXP, SEXP configSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type config(configSEXP);
    rcpp_result_gen = Rcpp::wrap(getAdFun(data, config));
    return rcpp_result_gen;
END_RCPP
}
// jointLogDens
double jointLogDens(const Rcpp::NumericVector& x, SEXP backendContext, SEXP Sgroups);
RcppExport SEXP _adlaplaceExample_jointLogDens(SEXP xSEXP, SEXP backendContextSEXP, SEXP SgroupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type backendContext(backendContextSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Sgroups(SgroupsSEXP);
    rcpp_result_gen = Rcpp::wrap(jointLogDens(x, backendContext, Sgroups));
    return rcpp_result_gen;
END_RCPP
}
// grad
Rcpp::NumericVector grad(const Rcpp::NumericVector& x, SEXP backendContext, const bool inner, SEXP Sgroups);
RcppExport SEXP _adlaplaceExample_grad(SEXP xSEXP, SEXP backendContextSEXP, SEXP innerSEXP, SEXP SgroupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type backendContext(backendContextSEXP);
    Rcpp::traits::input_parameter< const bool >::type inner(innerSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Sgroups(SgroupsSEXP);
    rcpp_result_gen = Rcpp::wrap(grad(x, backendContext, inner, Sgroups));
    return rcpp_result_gen;
END_RCPP
}
// hess
Rcpp::S4 hess(const Rcpp::NumericVector& x, SEXP backendContext, const bool inner, SEXP Sgroups);
RcppExport SEXP _adlaplaceExample_hess(SEXP xSEXP, SEXP backendContextSEXP, SEXP innerSEXP, SEXP SgroupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type backendContext(backendContextSEXP);
    Rcpp::traits::input_parameter< const bool >::type inner(innerSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Sgroups(SgroupsSEXP);
    rcpp_result_gen = Rcpp::wrap(hess(x, backendContext, inner, Sgroups));
    return rcpp_result_gen;
END_RCPP
}
// traceHinvT
Rcpp::NumericVector traceHinvT(const Rcpp::NumericVector& x, const Rcpp::S4& LinvPt, const Rcpp::S4& LinvPtColumns, SEXP backendContext, SEXP Sgroups);
RcppExport SEXP _adlaplaceExample_traceHinvT(SEXP xSEXP, SEXP LinvPtSEXP, SEXP LinvPtColumnsSEXP, SEXP backendContextSEXP, SEXP SgroupsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::S4& >::type LinvPt(LinvPtSEXP);
    Rcpp::traits::input_parameter< const Rcpp::S4& >::type LinvPtColumns(LinvPtColumnsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type backendContext(backendContextSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Sgroups(SgroupsSEXP);
    rcpp_result_gen = Rcpp::wrap(traceHinvT(x, LinvPt, LinvPtColumns, backendContext, Sgroups));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_adlaplaceExample_getAdFun", (DL_FUNC) &_adlaplaceExample_getAdFun, 2},
    {"_adlaplaceExample_jointLogDens", (DL_FUNC) &_adlaplaceExample_jointLogDens, 3},
    {"_adlaplaceExample_grad", (DL_FUNC) &_adlaplaceExample_grad, 4},
    {"_adlaplaceExample_hess", (DL_FUNC) &_adlaplaceExample_hess, 4},
    {"_adlaplaceExample_traceHinvT", (DL_FUNC) &_adlaplaceExample_traceHinvT, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_adlaplaceExample(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
