# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
test3 <- function(X, U, V, W) {
    .Call('_hpolcc_test3', PACKAGE = 'hpolcc', X, U, V, W)
}

#' @export
thirdDiagonals <- function(parameters, dataList, configList) {
    .Call('_hpolcc_thirdDiagonals', PACKAGE = 'hpolcc', parameters, dataList, configList)
}

#' @export
thirdNonDiagonalsSparsity <- function(parameters, dataList, configList, pairs) {
    .Call('_hpolcc_thirdNonDiagonalsSparsity', PACKAGE = 'hpolcc', parameters, dataList, configList, pairs)
}

#' @export
thirdOffDiagonals <- function(parameters, dataList, configList) {
    .Call('_hpolcc_thirdOffDiagonals', PACKAGE = 'hpolcc', parameters, dataList, configList)
}

#' @export
thirdDiagonalsStrata <- function(parameters, data, config, sparsity, strata) {
    .Call('_hpolcc_thirdDiagonalsStrata', PACKAGE = 'hpolcc', parameters, data, config, sparsity, strata)
}

#' @export
thirdOffDiagonalsStrata <- function(parameters, data, config, sparsity, strata) {
    .Call('_hpolcc_thirdOffDiagonalsStrata', PACKAGE = 'hpolcc', parameters, data, config, sparsity, strata)
}

#' @export
objectiveFunctionNoDiff <- function(x, data, config) {
    .Call('_hpolcc_objectiveFunctionNoDiff', PACKAGE = 'hpolcc', x, data, config)
}

#' @export
objectiveFunctionGrad <- function(x, data, config) {
    .Call('_hpolcc_objectiveFunctionGrad', PACKAGE = 'hpolcc', x, data, config)
}

#' @export
objectiveFunctionHessian <- function(parameters, dataList, configList) {
    .Call('_hpolcc_objectiveFunctionHessian', PACKAGE = 'hpolcc', parameters, dataList, configList)
}

#' @export
logLikNoQStrata <- function(parameters, data, config, strata, sparsity) {
    .Call('_hpolcc_logLikNoQStrata', PACKAGE = 'hpolcc', parameters, data, config, strata, sparsity)
}

#' @export
objectiveFunctionC <- function(parameters, dataList, configList) {
    .Call('_hpolcc_objectiveFunctionC', PACKAGE = 'hpolcc', parameters, dataList, configList)
}

