# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
thirdDiagonalsStrata <- function(parameters, data, config) {
    .Call('_hpolcc_thirdDiagonalsStrata', PACKAGE = 'hpolcc', parameters, data, config)
}

#' @export
getAdFun <- function(x, data, config) {
    .Call('_hpolcc_getAdFun', PACKAGE = 'hpolcc', x, data, config)
}

#' @export
jointLogDens <- function(x, data, config, adfun = NULL) {
    .Call('_hpolcc_jointLogDens', PACKAGE = 'hpolcc', x, data, config, adfun)
}

#' @export
grad <- function(parameters, data, config, adfun = NULL) {
    .Call('_hpolcc_grad', PACKAGE = 'hpolcc', parameters, data, config, adfun)
}

#' @export
hessian <- function(parameters, data, config, adfun = NULL) {
    .Call('_hpolcc_hessian', PACKAGE = 'hpolcc', parameters, data, config, adfun)
}

#' @export
hessianQdense <- function(parameters, data, config) {
    .Call('_hpolcc_hessianQdense', PACKAGE = 'hpolcc', parameters, data, config)
}

#' @export
hessianDense <- function(parameters, data, config) {
    .Call('_hpolcc_hessianDense', PACKAGE = 'hpolcc', parameters, data, config)
}

#' @export
hessianDenseLogical <- function(parameters, data, config) {
    .Call('_hpolcc_hessianDenseLogical', PACKAGE = 'hpolcc', parameters, data, config)
}

#' @export
gradLogical <- function(parameters, data, config) {
    .Call('_hpolcc_gradLogical', PACKAGE = 'hpolcc', parameters, data, config)
}

