# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
test3 <- function(X, U, V, W) {
    .Call('_hpolcc_test3', PACKAGE = 'hpolcc', X, U, V, W)
}

#' @export
thirdDiagonals <- function(parameters, dataList, configList) {
    .Call('_hpolcc_thirdDiagonals', PACKAGE = 'hpolcc', parameters, dataList, configList)
}

#' @export
thirdNonDiagonalsSparsity <- function(parameters, dataList, configList, pairs) {
    .Call('_hpolcc_thirdNonDiagonalsSparsity', PACKAGE = 'hpolcc', parameters, dataList, configList, pairs)
}

#' @export
thirdOffDiagonals <- function(parameters, dataList, configList) {
    .Call('_hpolcc_thirdOffDiagonals', PACKAGE = 'hpolcc', parameters, dataList, configList)
}

#' @export
objectiveFunctionNoDiff <- function(parameters, dataList, configList) {
    .Call('_hpolcc_objectiveFunctionNoDiff', PACKAGE = 'hpolcc', parameters, dataList, configList)
}

#' @export
objectiveFunctionGrad <- function(parameters, dataList, configList) {
    .Call('_hpolcc_objectiveFunctionGrad', PACKAGE = 'hpolcc', parameters, dataList, configList)
}

#' @export
objectiveFunctionHessian <- function(parameters, dataList, configList) {
    .Call('_hpolcc_objectiveFunctionHessian', PACKAGE = 'hpolcc', parameters, dataList, configList)
}

#' @export
objectiveFunctionHessian2 <- function(parameters, dataList, configList) {
    .Call('_hpolcc_objectiveFunctionHessian2', PACKAGE = 'hpolcc', parameters, dataList, configList)
}

#' @export
objectiveFunctionC <- function(parameters, dataList, configList) {
    .Call('_hpolcc_objectiveFunctionC', PACKAGE = 'hpolcc', parameters, dataList, configList)
}

lgamma_forward_deriv <- function(x, order) {
    .Call('_hpolcc_lgamma_forward_deriv', PACKAGE = 'hpolcc', x, order)
}

lgamma_reverse_deriv <- function(x, order) {
    .Call('_hpolcc_lgamma_reverse_deriv', PACKAGE = 'hpolcc', x, order)
}

logspaceadd_forward_deriv <- function(x, order) {
    .Call('_hpolcc_logspaceadd_forward_deriv', PACKAGE = 'hpolcc', x, order)
}

logspaceadd_inbuilt_deriv <- function(x, order) {
    .Call('_hpolcc_logspaceadd_inbuilt_deriv', PACKAGE = 'hpolcc', x, order)
}

testAddGammaR <- function(parameters) {
    .Call('_hpolcc_testAddGammaR', PACKAGE = 'hpolcc', parameters)
}

