# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Low-level C++ entry points (Rcpp exports)
#'
#' @param data An R list containing model data and matrices required by the AD
#'   construction. Required fields depend on the model (see vignette).
#' @param config An R list of configuration options (e.g., parameter vectors,
#'   sparsity options, threading options).
#' @param inner Logical; if TRUE, build the inner AD function; otherwise build
#'   the outer AD function.
#'
#' @param parameters Numeric vector of parameters for the requested operation
#'   (e.g., inner optimization or trace calculation). Interpretation depends on
#'   the backend/model.
#' @param control Control list for the optimizer (e.g., trust region settings,
#'   tolerances, max iterations). Used by `inner_opt()`.
#' @param adPackFull,adPack Optional external pointer (`externalptr`) returned by
#'   `getAdFun()`. If provided, reuse cached AD objects / sparsity structures.
#'
#' @param LinvPt,LinvPtColumns Sparse matrix objects (S4, typically from Matrix)
#'   used by `traceHinvT()`; see package documentation/vignette for required
#'   classes and dimensions.
#'
#' @return `getAdFun()` returns an external pointer (`externalptr`) to an
#'   internal AD object. 
#'
#'
#' @details
#' The returned pointer is not human-readable and should not be modified.
#' It may hold substantial memory (tapes, sparsity patterns, caches). Use
#' package-level functions to manage lifecycle and computation.
#'
#' @rdname adlaplace_cpp
#' @export
getAdFun <- function(data, config, inner = FALSE) {
    .Call(`_adlaplaceExample_getAdFun`, data, config, inner)
}

#' @rdname adlaplace_cpp
#' @export
inner_opt <- function(parameters, data, control, config, adPackFull = NULL) {
    .Call(`_adlaplaceExample_inner_opt`, parameters, data, control, config, adPackFull)
}

#' @rdname adlaplace_cpp
#' @export
inner_opt_adpack <- function(parameters, adPack, control, config, adPackFull = NULL) {
    .Call(`_adlaplaceExample_inner_opt_adpack`, parameters, adPack, control, config, adPackFull)
}

#' @rdname adlaplace_cpp
#' @export
traceHinvT <- function(parameters, LinvPt, LinvPtColumns, config, adPack = NULL) {
    .Call(`_adlaplaceExample_traceHinvT`, parameters, LinvPt, LinvPtColumns, config, adPack)
}

#' @rdname adlaplace_cpp
#' @export
sparsity <- function(data, config) {
    .Call(`_adlaplaceExample_sparsity`, data, config)
}

