# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Build observation-shard \code{ad_fun_ptr} in this package's shared library.
#'
#' @param model \code{ad_data} S4 object.
#' @param config Model configuration list.
#' @param name Observation density name (e.g. \code{"dirichlet_multinomial"}).
#' @return External pointer of class \code{ad_fun_ptr}.
get_ad_fun_raw_obs <- function(model, config, name) {
    .Call(`_hpolcc_get_ad_fun_raw_obs`, model, config, name)
}

#' Build parameters-shard \code{ad_fun_ptr} in this package's shared library.
#'
#' @param model \code{ad_data} S4 object.
#' @param config Model configuration list.
#' @param name Parameters density name (e.g. \code{"dirichlet_multinomial_extra"}).
#' @return External pointer of class \code{ad_fun_ptr}.
get_ad_fun_raw_parameters <- function(model, config, name) {
    .Call(`_hpolcc_get_ad_fun_raw_parameters`, model, config, name)
}

