# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Build raw AD pack external pointer (hpolcc)
#'
#' @param data Model data list.
#' @param config Model configuration list.
#' @return External pointer of class \code{adlaplace_handle_ptr}.
#' @keywords internal
get_ad_fun_raw_hpolcc <- function(data, config) {
    .Call(`_hpolcc_get_ad_fun_raw_hpolcc`, data, config)
}

