# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sparse LDL log-determinant of a FEM precision at given (range, sd)
#'
#' Exercises the same \code{chol_update_csc} path used by
#' \code{random_fem_det_*}. Useful for diagnosing non-finite joint densities.
#'
#' @param precision List from \code{\link{fem_precision_payload}}.
#' @param range,sd Practical range and field SD (natural or log scale).
#' @param log_scale Logical length-1 or length-2: whether \code{range}/\code{sd}
#'   are already on the log scale. Default \code{FALSE} (\code{NULL}).
#' @return List with \code{logdet}, \code{coef}, \code{D}, \code{first_bad},
#'   \code{n_bad}, \code{n}, \code{alpha}.
#' @export
fem_logdet_debug <- function(precision, range, sd, log_scale = NULL) {
    .Call(`_adlaplaceFem_fem_logdet_debug`, precision, range, sd, log_scale)
}

#' Build raw AD handle for a random_fem_ssq_2 term
#'
#' @param model An \code{density_data} S4 object with FEM precision payload.
#' @param config Model configuration list.
#' @return External pointer of class \code{ad_pack_ptr}.
#' @keywords internal
#' @noRd
create_ad_shard_random_fem_ssq_2 <- function(model, config) {
    .Call(`_adlaplaceFem_create_ad_shard_random_fem_ssq_2`, model, config)
}

#' Build raw AD handle for a random_fem_ssq_3 term
#'
#' @param model An \code{density_data} S4 object with FEM precision payload.
#' @param config Model configuration list.
#' @return External pointer of class \code{ad_pack_ptr}.
#' @keywords internal
#' @noRd
create_ad_shard_random_fem_ssq_3 <- function(model, config) {
    .Call(`_adlaplaceFem_create_ad_shard_random_fem_ssq_3`, model, config)
}

#' Build parameters-shard \code{ad_pack_ptr} for FEM log-determinant densities.
#'
#' @param model \code{density_data} S4 object with FEM precision payload.
#' @param config Model configuration list.
#' @param name Density name (\code{"random_fem_det_2"} or \code{"random_fem_det_3"}).
#' @return External pointer of class \code{ad_pack_ptr}.
#' @keywords internal
#' @noRd
get_ad_pack_raw_parameters <- function(model, config, name) {
    .Call(`_adlaplaceFem_get_ad_pack_raw_parameters`, model, config, name)
}

