# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Backend AD builder for hpolcc
#'
#' Builds model-specific AD tapes/metadata for this backend package.
#' Evaluation should be done through \pkg{adlaplace} functions
#' (\code{jointLogDens()}, \code{grad()}, \code{hess()}, \code{traceHinvT()}).
#'
#' @param data Model data list.
#' @param config Model configuration list.
#'
#' @return List with backend handle/sparsity metadata used by \pkg{adlaplace}.
#'
#' @name adlaplace_backend_cpp
NULL

#' @rdname adlaplace_backend_cpp
#' @export
getAdFun_r <- function(data, config) {
    .Call(`_hpolcc_getAdFun_r`, data, config)
}

