# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export	
getAdFun <- function(data, config, inner = FALSE) {
    .Call(`_hpolcc_getAdFun`, data, config, inner)
}

#' @export
jointLogDensNoAdfun <- function(parameters, data, config) {
    .Call(`_hpolcc_jointLogDensNoAdfun`, parameters, data, config)
}

#' @export
jointLogDens <- function(parameters, adPack, config) {
    .Call(`_hpolcc_jointLogDens`, parameters, adPack, config)
}

#' @export
grad <- function(parameters, adPack, config) {
    .Call(`_hpolcc_grad`, parameters, adPack, config)
}

#' @export
hessian <- function(parameters, adPack, config) {
    .Call(`_hpolcc_hessian`, parameters, adPack, config)
}

#' @export
inner_opt <- function(parameters, data, control, config) {
    .Call(`_hpolcc_inner_opt`, parameters, data, control, config)
}

#' @export
inner_opt_adpack <- function(parameters, adPack, control, config) {
    .Call(`_hpolcc_inner_opt_adpack`, parameters, adPack, control, config)
}

#' @export
traceHinvT <- function(parameters, LinvPt, LinvPtColumns, config, adPack = NULL) {
    .Call(`_hpolcc_traceHinvT`, parameters, LinvPt, LinvPtColumns, config, adPack)
}

#' @export
sparsity <- function(data, config) {
    .Call(`_hpolcc_sparsity`, data, config)
}

