# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
getAdFun_r <- function(data, config, inner = FALSE) {
    .Call(`_hpolcc_getAdFun_r`, data, config, inner)
}

#' @export
jointLogDensNoAdfun <- function(parameters, data, config) {
    .Call(`_hpolcc_jointLogDensNoAdfun`, parameters, data, config)
}

#' @export
jointLogDens <- function(parameters, adFun, config) {
    .Call(`_hpolcc_jointLogDens`, parameters, adFun, config)
}

#' @export
grad <- function(parameters, adFun, config) {
    .Call(`_hpolcc_grad`, parameters, adFun, config)
}

#' @export
hessian <- function(parameters, adFun, config) {
    .Call(`_hpolcc_hessian`, parameters, adFun, config)
}

#' @export
inner_opt <- function(parameters, data, control, config, adFun = NULL) {
    .Call(`_hpolcc_inner_opt`, parameters, data, control, config, adFun)
}

#' @export
inner_opt_adpack <- function(parameters, adFun, control, config, adFunFull = NULL) {
    .Call(`_hpolcc_inner_opt_adpack`, parameters, adFun, control, config, adFunFull)
}

#' @export
traceHinvT <- function(parameters, LinvPt, LinvPtColumns, config, adFun = NULL) {
    .Call(`_hpolcc_traceHinvT`, parameters, LinvPt, LinvPtColumns, config, adFun)
}

#' @export
sparsity <- function(data, config) {
    .Call(`_hpolcc_sparsity`, data, config)
}

