name: R-CMD-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    container: rocker/r2u
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          apt-get update -qq 
          apt-get install -y \
            r-cran-data.table r-cran-numderiv r-cran-abind \
            r-cran-quarto r-cran-rcpp r-cran-trustoptim r-cran-sn \
            r-cran-get r-cran-timedate r-cran-woodburymatrix \
            libcppad-dev libgmp-dev libomp-dev \
            libcurl4-openssl-dev libuv1-dev curl wget

      - name: Set up Quarto
        run: |
          curl -L -o quarto.deb \
            "https://github.com/quarto-dev/quarto-cli/releases/download/v1.5.29/quarto-1.5.29-linux-amd64.deb"
          apt-get install -y ./quarto.deb

      - name: Install TinyTeX
        run: |
          Rscript -e "install.packages('tinytex', repos = 'https://cloud.r-project.org/')"
          Rscript -e "tinytex::install_tinytex()"
          echo "$(Rscript -e 'cat(tinytex:::tl_path())')/bin" >> $GITHUB_PATH
 

      - name: build
        run: |
          R CMD build adlaplace
          R CMD INSTALL adlaplace_*.gz
          R CMD build adlaplaceExample

      - name: check adlaplace
        run: |
          R CMD check adlaplace_*.gz

      - name: check adlaplaceExample
        run: |
          R CMD check adlaplaceExample*.gz

      - name: build hpolcc
        run: |
          R CMD build hpolcc

      - name: check hpolcc
        run: |
          R CMD check hpolcc*.gz
